ALTER TABLE Ticket MODIFY COLUMN status ENUM('OPEN','CONFIRMED','CHECKED_IN','IN_PROGRESS','READY','CLOSED','CANCELLED','NO_SHOW') NOT NULL DEFAULT 'OPEN';
ALTER TABLE Ticket ADD COLUMN noShowFeeCents INT NULL;
ALTER TABLE Ticket ADD COLUMN noShowProcessedAt DATETIME(3) NULL;
ALTER TABLE Ticket ADD COLUMN noShowProcessedByUserId VARCHAR(191) NULL;
ALTER TABLE Ticket ADD COLUMN noShowPaymentMethodId VARCHAR(191) NULL;
ALTER TABLE Ticket ADD INDEX Ticket_tenantId_noShowProcessedAt_idx (tenantId, noShowProcessedAt);
