import {db} from './db';
import {normalizePhone} from './customer';
export type SmsConfig={accountSid:string;authToken:string;from:string;webhookUrl?:string};
export function configFor(tenantId:string):SmsConfig|null{try{const all=JSON.parse(process.env.GROOMPRO_SMS_TENANTS_JSON||'{}');const c=all[tenantId];return c&&/^AC[0-9a-f]{32}$/i.test(c.accountSid)&&c.authToken&&/^\+[1-9]\d{7,14}$/.test(c.from)?c:null}catch{return null}}
export function smsCallbackUrl(config:SmsConfig,tenantId:string,communicationId=''){try{if(!config.webhookUrl)return null;const url=new URL(config.webhookUrl);if(url.protocol!=='https:'||url.search||url.hash||url.username||url.password)return null;url.searchParams.set('tenantId',tenantId);if(communicationId)url.searchParams.set('communicationId',communicationId);return url.toString()}catch{return null}}
export const smsConfigured=(tenantId:string)=>!!configFor(tenantId);
export async function sendCustomerSms({tenantId,customerId,ticketId,phoneId,body,subject}:{tenantId:string;customerId:string;ticketId?:string;phoneId?:string;body:string;subject?:string}){
 if(!body.trim()||body.length>1600)throw Error('Message must contain 1–1600 characters.');
 const customer=await db.customer.findFirst({where:{id:customerId,tenantId,active:true},include:{phones:{where:{smsEnabled:true},orderBy:{isPrimary:'desc'}}}});if(!customer)throw Error('Customer not found.');
 const phone=phoneId?customer.phones.find(p=>p.id===phoneId):customer.phones[0];if(!phone)throw Error('Choose an SMS-enabled phone belonging to this customer.');
 const digits=normalizePhone(phone.number),to=phone.number.trim().startsWith('+')?'+'+phone.number.replace(/\D/g,''):digits.length===10?'+1'+digits:'+'+digits;
 if(!/^\+[1-9]\d{7,14}$/.test(to))throw Error('Use a valid international phone number.');
 if(ticketId&&!await db.ticket.findFirst({where:{id:ticketId,tenantId,customerId}}))throw Error('Ticket does not belong to this customer.');
 const config=configFor(tenantId);const communication=await db.communication.create({data:{tenantId,customerId,ticketId:ticketId||null,channel:'SMS',direction:'OUTBOUND',toAddress:to,fromAddress:config?.from||null,subject:subject||null,body,deliveryStatus:config?'SENDING':'NOT_CONFIGURED'}});
 if(!config)return{communication,message:'SMS is not configured for this business. The message was saved but not sent.'};
 try{const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${config.accountSid}/Messages.json`,{method:'POST',headers:{Authorization:'Basic '+Buffer.from(config.accountSid+':'+config.authToken).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({To:to,From:config.from,Body:body,...(smsCallbackUrl(config,tenantId,communication.id)?{StatusCallback:smsCallbackUrl(config,tenantId,communication.id)!}:{})}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok){const failed=await db.communication.update({where:{id:communication.id},data:{deliveryStatus:'FAILED',deliveryError:'Provider rejected the message. Check the messaging account.'}});return{communication:failed,message:'The provider rejected the message.'}}const status=String(result.status||'queued').toUpperCase();await db.communication.updateMany({where:{id:communication.id,deliveryStatus:'SENDING'},data:{externalId:result.sid,deliveryStatus:status,sentAt:['SENT','DELIVERED'].includes(status)?new Date():null}});const updated=await db.communication.findUniqueOrThrow({where:{id:communication.id}});return{communication:updated,message:'Message accepted by the SMS provider ('+status.toLowerCase()+').'}}
 catch{await db.communication.updateMany({where:{id:communication.id,deliveryStatus:'SENDING'},data:{deliveryStatus:'UNKNOWN',deliveryError:'Delivery outcome unknown. Check provider before retrying.'}});const unknown=await db.communication.findUniqueOrThrow({where:{id:communication.id}});return{communication:unknown,message:'Delivery outcome is unknown. Check the provider before resending.'}}
}
