import {writeAudit} from '@/src/lib/audit';
import {getActiveEmployeeSession} from '@/src/lib/employee-session';
import {sendCustomerSms} from '@/src/lib/sms';
import {normalizePhone} from '@/src/lib/customer';
import {NextRequest,NextResponse} from "next/server";
import {db} from "@/src/lib/db";
async function tenant(r:NextRequest){const explicit=r.headers.get("x-tenant-id")||r.cookies.get("groompro_tenant")?.value||process.env.GROOMPRO_DEV_TENANT_ID||null;return explicit}
export async function GET(r:NextRequest){const t=await tenant(r);if(!t)return NextResponse.json({error:"Business setup is not complete yet."},{status:503});const rows=await db.communication.findMany({where:{tenantId:t},include:{customer:{select:{firstName:true,lastName:true}}},orderBy:{createdAt:"desc"},take:100});return NextResponse.json({communications:rows})}
export async function POST(r:NextRequest){const t=await tenant(r);if(!t)return NextResponse.json({error:'Business context required.'},{status:401});const sid=r.cookies.get('groompro_session')?.value,session=sid?await getActiveEmployeeSession(t,sid):null;if(!session)return NextResponse.json({error:'Employee PIN is required.'},{status:401});try{const b=await r.json();if(b.channel==='EMAIL'){const customer=await db.customer.findFirst({where:{id:String(b.customerId||''),tenantId:t,active:true}});const body=String(b.body||'').trim();if(!customer?.email||!body||body.length>10000)throw Error('Choose a customer with an email address and enter a message.');const communication=await db.communication.create({data:{tenantId:t,customerId:customer.id,channel:'EMAIL',direction:'OUTBOUND',body,toAddress:customer.email,deliveryStatus:'NOT_CONFIGURED'}});await writeAudit({tenantId:t,actorUserId:session.user.id,entityType:'COMMUNICATION',entityId:communication.id,customerId:customer.id,action:'EMAIL_SAVED',summary:'Saved email draft; provider not configured.'});return NextResponse.json({communication,message:'Email delivery is not configured. The message was saved but not sent.'},{status:201})}if(b.channel&&b.channel!=='SMS')throw Error('Choose SMS or email.');let phoneId=b.phoneId;if(b.toAddress){const phone=await db.customerPhone.findFirst({where:{tenantId:t,customerId:String(b.customerId),normalized:normalizePhone(String(b.toAddress)),smsEnabled:true}});if(!phone)throw Error('Select a customer-associated SMS number.');phoneId=phone.id}const result=await sendCustomerSms({tenantId:t,customerId:String(b.customerId||''),phoneId,body:String(b.body||'')});await writeAudit({tenantId:t,actorUserId:session.user.id,entityType:"COMMUNICATION",entityId:result.communication.id,customerId:String(b.customerId),action:"MESSAGE",summary:result.message});return NextResponse.json(result,{status:201})}catch(e){return NextResponse.json({error:String(e)},{status:400})}}
