ALTER TABLE `Customer`
  ADD COLUMN `address1` VARCHAR(191) NULL,
  ADD COLUMN `address2` VARCHAR(191) NULL,
  ADD COLUMN `city` VARCHAR(191) NULL,
  ADD COLUMN `state` VARCHAR(191) NULL,
  ADD COLUMN `postalCode` VARCHAR(191) NULL;
