const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm');
function route(file,db,role='ADMIN') {const exports={};const dependencies={'next/server':{NextResponse:{json:(body,opts)=>({body,status:opts?.status||200})}},'@/src/lib/db':{db},'@/src/lib/customer':{getCustomerProfile:async()=>({id:'customer'})},'@/src/lib/pin':{hashPin:async()=> 'new-hash'},'@/src/lib/employee-session':{getActiveEmployeeSession:async()=>role?{user:{id:'actor',role}}:null},'node:crypto':require('node:crypto')};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:name=>{if(!(name in dependencies))throw Error(name);return dependencies[name]},process});return exports;}
const request=body=>({headers:{get:()=> 'tenant'},cookies:{get:()=>({value:'session'})},json:async()=>body});
test('weekly schedules accept Sunday but reject invalid clocks, fractional days and reversed shifts',async()=>{let writes=0;const api=route('app/api/employee-schedules/route.ts',{user:{findFirst:async()=>({id:'employee'})},$executeRaw:async()=>{writes++}});const base={userId:'employee',dayOfWeek:0,startTime:'08:30',endTime:'17:00'};assert.equal((await api.PUT(request(base))).status,200);for(const change of [{dayOfWeek:1.5},{startTime:'25:00'},{endTime:'12:99'},{startTime:'18:00'},{dayOfWeek:7}])assert.equal((await api.PUT(request({...base,...change}))).status,400);assert.equal(writes,1)});
test('schedule changes require a signed-in manager and enforce employee tenant membership',async()=>{for(const [role,status] of [[null,401],['BACK',403],['ADMIN',404]]){const api=route('app/api/employee-schedules/route.ts',{user:{findFirst:async()=>null}},role);assert.equal((await api.PUT(request({userId:'other-tenant',dayOfWeek:1,startTime:'08:00',endTime:'17:00'}))).status,status)}});
test('employee profile edits preserve PIN and permissions when omitted, and allow outside marketing',async()=>{let saved;const api=route('app/api/employees/route.ts',{user:{findFirst:async()=>({id:'employee'}),update:async({data})=>{saved=data;return{id:'employee',...data}}}});assert.equal((await api.PATCH(request({id:'employee',firstName:'Rudy',jobTitle:'Paw Walker',locationId:'',pin:''}))).status,200);assert.equal(saved.firstName,'Rudy');assert.equal(saved.jobTitle,'Paw Walker');assert.equal(saved.locationId,null);assert.equal('pinHash' in saved,false);assert.equal('role' in saved,false)});
test('employee edits reject blank names, invalid roles, and another tenant location',async()=>{const api=route('app/api/employees/route.ts',{location:{findFirst:async()=>null},user:{findFirst:async()=>({id:'employee'})}});for(const change of [{firstName:' '},{role:'SUPERUSER'},{locationId:'other'}])assert.equal((await api.PATCH(request({id:'employee',...change}))).status,400)});

test('customer edits are tenant scoped and cannot overwrite account balances or pet records',async()=>{let update;const api=route('app/api/customers/[customerId]/route.ts',{customer:{updateMany:async data=>{update=data;return{count:1}}}});const response=await api.PATCH(request({firstName:'Jane',lastName:'Example',email:'jane@example.com',notes:'Updated',balanceCents:0,pets:[]}),{params:Promise.resolve({customerId:'customer'})});assert.equal(response.status,200);assert.equal(update.where.tenantId,'tenant');assert.equal(update.where.id,'customer');assert.deepEqual(Object.keys(update.data).sort(),['email','firstName','lastName','notes']);});
test('customer edits require a PIN and reject blank names or malformed email',async()=>{const api=route('app/api/customers/[customerId]/route.ts',{});for(const body of [{firstName:'',lastName:'Example'},{firstName:'Jane',lastName:'Example',email:'bad'}])assert.equal((await api.PATCH(request(body),{params:Promise.resolve({customerId:'customer'})})).status,400);const unauth=route('app/api/customers/[customerId]/route.ts',{},null);assert.equal((await unauth.PATCH(request({}),{params:Promise.resolve({customerId:'customer'})})).status,401)});
