const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm');
function route(file,db,role='ADMIN') {const exports={};const dependencies={'next/server':{NextResponse:{json:(body,opts)=>({body,status:opts?.status||200})}},'@/src/lib/db':{db},'@/src/lib/customer':{getCustomerProfile:async()=>({id:'customer'})},'@/src/lib/pin':{hashPin:async()=> 'new-hash'},'@/src/lib/employee-session':{getActiveEmployeeSession:async()=>role?{user:{id:'actor',role}}:null},'@/src/lib/schedule-dates':(()=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/schedule-dates.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,Date});return exports})(),'node:crypto':require('node:crypto')};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:name=>{if(!(name in dependencies))throw Error(name);return dependencies[name]},process});return exports;}
const request=body=>({headers:{get:()=> 'tenant'},cookies:{get:()=>({value:'session'})},json:async()=>body});
test('weekly schedules accept Sunday but reject invalid clocks, fractional days and reversed shifts',async()=>{let writes=0;const api=route('app/api/employee-schedules/route.ts',{user:{findFirst:async()=>({id:'employee'})},$executeRaw:async()=>{writes++}});const base={userId:'employee',dayOfWeek:0,startTime:'08:30',endTime:'17:00'};assert.equal((await api.PUT(request(base))).status,200);for(const change of [{dayOfWeek:1.5},{startTime:'25:00'},{endTime:'12:99'},{startTime:'18:00'},{dayOfWeek:7}])assert.equal((await api.PUT(request({...base,...change}))).status,400);assert.equal(writes,1)});
test('schedule changes require a signed-in manager and enforce employee tenant membership',async()=>{for(const [role,status] of [[null,401],['BACK',403],['ADMIN',404]]){const api=route('app/api/employee-schedules/route.ts',{user:{findFirst:async()=>null}},role);assert.equal((await api.PUT(request({userId:'other-tenant',dayOfWeek:1,startTime:'08:00',endTime:'17:00'}))).status,status)}});
test('employee profile edits preserve PIN and permissions when omitted, and allow outside marketing',async()=>{let saved;const api=route('app/api/employees/route.ts',{user:{findFirst:async()=>({id:'employee'}),update:async({data})=>{saved=data;return{id:'employee',...data}}}});assert.equal((await api.PATCH(request({id:'employee',firstName:'Rudy',jobTitle:'Paw Walker',locationId:'',pin:''}))).status,200);assert.equal(saved.firstName,'Rudy');assert.equal(saved.jobTitle,'Paw Walker');assert.equal(saved.locationId,null);assert.equal('pinHash' in saved,false);assert.equal('role' in saved,false)});
test('employee edits reject blank names, invalid roles, and another tenant location',async()=>{const api=route('app/api/employees/route.ts',{location:{findFirst:async()=>null},user:{findFirst:async()=>({id:'employee'})}});for(const change of [{firstName:' '},{role:'SUPERUSER'},{locationId:'other'}])assert.equal((await api.PATCH(request({id:'employee',...change}))).status,400)});

test('customer edits are tenant scoped and cannot overwrite account balances or pet records',async()=>{let update;const api=route('app/api/customers/[customerId]/route.ts',{customer:{updateMany:async data=>{update=data;return{count:1}}}});const response=await api.PATCH(request({firstName:'Jane',lastName:'Example',email:'jane@example.com',notes:'Updated',balanceCents:0,pets:[]}),{params:Promise.resolve({customerId:'customer'})});assert.equal(response.status,200);assert.equal(update.where.tenantId,'tenant');assert.equal(update.where.id,'customer');assert.deepEqual(Object.keys(update.data).sort(),['email','firstName','lastName','notes']);});
test('customer edits require a PIN and reject blank names or malformed email',async()=>{const api=route('app/api/customers/[customerId]/route.ts',{});for(const body of [{firstName:'',lastName:'Example'},{firstName:'Jane',lastName:'Example',email:'bad'}])assert.equal((await api.PATCH(request(body),{params:Promise.resolve({customerId:'customer'})})).status,400);const unauth=route('app/api/customers/[customerId]/route.ts',{},null);assert.equal((await unauth.PATCH(request({}),{params:Promise.resolve({customerId:'customer'})})).status,401)});

test('editing existing recurring hours updates the selected shift instead of inserting a duplicate',async()=>{let statement='';const api=route('app/api/employee-schedules/route.ts',{user:{findFirst:async()=>({id:'e'})},$queryRaw:async()=>[{id:'s'}],$executeRaw:async parts=>{statement=parts.join('?');return 0}});assert.equal((await api.PUT(request({userId:'e',id:'s',dayOfWeek:1,startTime:'09:00',endTime:'17:00'}))).status,200);assert.match(statement,/UPDATE EmployeeSchedule/);assert.doesNotMatch(statement,/INSERT/)});
test('date-only overrides save and reset by tenant, resource, and date without changing recurrence',async()=>{let saved,deleted;const api=route('app/api/schedule-overrides/route.ts',{user:{findFirst:async()=>({id:'e'})},scheduleOverride:{upsert:async v=>{saved=v},deleteMany:async v=>{deleted=v}}});const body={resourceKind:'employee',resourceId:'e',date:'2026-10-05',dayOff:true};assert.equal((await api.PUT({...request(body),method:'PUT'})).status,200);assert.equal(saved.create.tenantId,'tenant');assert.equal(saved.create.dayOff,true);assert.equal(saved.create.startTime,null);assert.equal((await api.DELETE({...request(body),method:'DELETE'})).status,200);assert.equal(deleted.where.resourceId,'e');assert.equal(deleted.where.date,'2026-10-05');assert.equal(deleted.where.tenantId,'tenant')});
test('date overrides reject foreign resources and nonmanagers',async()=>{const body={resourceKind:'employee',resourceId:'foreign',date:'2026-10-05',dayOff:true};for(const [role,status] of [[null,401],['BACK',403],['ADMIN',404]]){const api=route('app/api/schedule-overrides/route.ts',{user:{findFirst:async()=>null}},role);assert.equal((await api.PUT({...request(body),method:'PUT'})).status,status)}});

test('pet creation links to a verified owner in the current business',async()=>{let lookup,created;const api=route('app/api/pets/route.ts',{customer:{findFirst:async v=>{lookup=v;return{id:'owner'}}},pet:{create:async v=>{created=v;return{id:'pet',...v.data}}}});const r=await api.POST(request({customerId:'owner',name:'Buddy',breed:'Poodle',notes:'Gentle',tenantId:'foreign'}));assert.equal(r.status,201);assert.equal(lookup.where.tenantId,'tenant');assert.equal(created.data.customerId,'owner');assert.equal(created.data.tenantId,'tenant')});
test('pet editing cannot transfer ownership or overwrite another family pet',async()=>{let update;const api=route('app/api/pets/route.ts',{customer:{findFirst:async()=>({id:'wrong-owner'})},pet:{updateMany:async v=>{update=v;return{count:0}}}});assert.equal((await api.PATCH(request({id:'pet',customerId:'wrong-owner',name:'Buddy'}))).status,404);assert.equal(update.where.customerId,'wrong-owner');assert.equal(update.where.tenantId,'tenant');assert.equal('customerId' in update.data,false);assert.equal('tenantId' in update.data,false)});
test('pet changes require PIN, valid owner, and a name',async()=>{const base={customerId:'owner',name:'Buddy'};assert.equal((await route('app/api/pets/route.ts',{},null).POST(request(base))).status,401);assert.equal((await route('app/api/pets/route.ts',{customer:{findFirst:async()=>null}}).POST(request(base))).status,404);assert.equal((await route('app/api/pets/route.ts',{}).POST(request({...base,name:' '}))).status,400)});
test('pet edits preserve vaccinations and owner while updating allowed fields',async()=>{let update;const pet={id:'pet',customerId:'owner',name:'Buddy',vaccinations:[{id:'v'}]};const api=route('app/api/pets/route.ts',{customer:{findFirst:async()=>({id:'owner'})},pet:{updateMany:async v=>{update=v;return{count:1}},findFirst:async()=>pet}});const r=await api.PATCH(request({...pet,breed:'Poodle',notes:'Gentle',vaccinations:[]}));assert.equal(r.status,200);assert.equal(r.body.pet.vaccinations.length,1);assert.deepEqual(Object.keys(update.data).sort(),['breed','name','notes'])});
test('pet listing searches individual pets with tenant-scoped owner information',async()=>{let query;const api=route('app/api/pets/route.ts',{pet:{findMany:async v=>{query=v;return[]}}});const r=await api.GET({...request({}),nextUrl:{searchParams:new URLSearchParams('q=Buddy')}});assert.equal(r.status,200);assert.equal(query.where.tenantId,'tenant');assert.equal(query.where.customer.tenantId,'tenant');assert.equal(query.where.OR[0].name.contains,'Buddy');assert.equal(query.include.customer.select.id,true)});
test('pet assigned package must belong to this business and remain active',async()=>{let lookup;const api=route('app/api/pets/route.ts',{customer:{findFirst:async()=>({id:'owner'})},package:{findFirst:async v=>{lookup=v;return null}}});const r=await api.PATCH(request({id:'pet',customerId:'owner',name:'Buddy',preferredPackageId:'foreign'}));assert.equal(r.status,400);assert.equal(lookup.where.tenantId,'tenant');assert.equal(lookup.where.active,true)});
