import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { db } from "@/src/lib/db";
const plan:[string,string,number[],string,string][]=[
["Edmundo","Saenz",[1,2,3,4,5],"08:00","17:00"],["Zagla","Saenz",[2,3,4,5,6],"08:00","17:00"],
["Abby","Ensing",[1,2,3,5,6],"08:00","17:00"],["Zagla","Paz",[1,2,4,5,6],"08:00","17:00"],
["Ruby","Paz",[1,2,3,4,5],"08:30","17:00"],["Arianna","Petro",[2,3,4,5,6],"08:30","17:00"],
["Lisa","Allen",[2,3,4,5,6],"08:30","17:00"],["Kandance","Krueger",[1,3,4,5,6],"08:30","17:00"],
["Hailey","Puly",[1,2,3,4,5],"08:30","17:00"],["Lyndsey","Culwell",[1,2,3,5,6],"08:30","17:00"],["Anton","Johnson",[1,2,4,5,6],"08:30","17:00"]
];
const assetHours=["08:30","17:00"];
export async function POST(r:NextRequest){const secret=process.env.GROOMPRO_SETUP_SECRET||"";const body=await r.json().catch(()=>({}));if(!secret||body.secret!==secret)return NextResponse.json({error:"Invalid setup secret."},{status:401});const tenant=await db.tenant.findFirst({orderBy:{createdAt:"asc"}});if(!tenant)return NextResponse.json({error:"Run the main preview seed first."},{status:400});await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS EmployeeSchedule (id VARCHAR(191) NOT NULL PRIMARY KEY, tenantId VARCHAR(191) NOT NULL, userId VARCHAR(191) NOT NULL, dayOfWeek INT NOT NULL, startTime VARCHAR(5) NOT NULL, endTime VARCHAR(5) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY uq_employee_schedule (userId,dayOfWeek), KEY idx_employee_schedule_tenant (tenantId,userId,dayOfWeek))`);await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS BookingAssetSchedule (id VARCHAR(191) NOT NULL PRIMARY KEY, tenantId VARCHAR(191) NOT NULL, assetId VARCHAR(191) NOT NULL, dayOfWeek INT NOT NULL, startTime VARCHAR(5) NOT NULL, endTime VARCHAR(5) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY uq_asset_schedule (assetId,dayOfWeek), KEY idx_asset_schedule_tenant (tenantId,assetId,dayOfWeek))`);let count=0;for(const [first,last,days,start,end] of plan){const user=await db.user.findFirst({where:{tenantId:tenant.id,firstName:first,lastName:last}});if(!user)continue;await db.$executeRaw`DELETE FROM EmployeeSchedule WHERE userId=${user.id}`;for(const day of days){await db.$executeRaw`INSERT INTO EmployeeSchedule (id,tenantId,userId,dayOfWeek,startTime,endTime,active) VALUES (${randomUUID()},${tenant.id},${user.id},${day},${start},${end},1)`;count++;}}const assets=await db.$queryRaw<Array<{id:string}>>`SELECT id FROM BookingAsset WHERE tenantId=${tenant.id}`;for(const a of assets){await db.$executeRaw`DELETE FROM BookingAssetSchedule WHERE assetId=${a.id}`;for(let day=1;day<=6;day++)await db.$executeRaw`INSERT INTO BookingAssetSchedule (id,tenantId,assetId,dayOfWeek,startTime,endTime,active) VALUES (${randomUUID()},${tenant.id},${a.id},${day},${assetHours[0]},${assetHours[1]},1)`;}return NextResponse.json({ok:true,employeeScheduleRows:count,assetScheduleRows:assets.length*6});}
