"use client";
import {useEffect,useState} from "react";
type SetupStatus={setupRequired:boolean;setupSecretConfigured:boolean;tenant?:{name:string};error?:string};
export default function SetupPage(){
 const[secret,setSecret]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[status,setStatus]=useState<SetupStatus|null>(null);const[complete,setComplete]=useState(false);
 useEffect(()=>{fetch("/api/setup/context",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Setup status unavailable.");setStatus(d)}).catch(e=>setMessage(e.message))},[]);
 async function seed(){setBusy(true);setMessage("");try{const r=await fetch("/api/setup/seed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({secret})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Setup failed.");setMessage(`Ready: ${d.seeded.customerCount} customers, ${d.seeded.employeeCount} employees, ${d.seeded.assetCount} booking assets, their schedules, and ${d.seeded.demoAppointmentCount} new appointments.`);setComplete(true);setSecret("")}catch(e){setMessage(e instanceof Error?e.message:"Setup failed.")}finally{setBusy(false)}}
 return <main style={{maxWidth:640,margin:"48px auto",padding:24}}><h1>GroomPro Setup</h1><p>{status?.setupRequired?"Your database is connected. Load the preview data to create Rubber Doggies Grooming and open the app.":status?.tenant?`Business: ${status.tenant.name}`:"Checking your business database…"}</p><p>Preview data includes 100 sample customers and pets, 11 employees, booking assets, work schedules, and appointments.</p>{status&&!status.setupSecretConfigured?<p role="alert">Set GROOMPRO_SETUP_SECRET in GoDaddy’s app environment settings, redeploy, and return here to enter that same secret.</p>:<><label htmlFor="setup-secret">Setup secret</label><input id="setup-secret" type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="off" style={{display:"block",width:"100%",padding:12,margin:"12px 0"}}/><button onClick={seed} disabled={busy||!secret||!status}>{busy?"Loading customers and schedules…":"Load Preview Data"}</button></>}{message&&<p role="status">{message}</p>}{(complete||status?.tenant)&&<p><a href="/">Open GroomPro</a></p>}</main>
}
