"use client";
import {useEffect,useRef,useState} from "react";
import {PinRequest} from "../lib/employee-fetch";
export function ActionPin({onSignedIn}:{onSignedIn:(employee:any)=>void}){
 const[open,setOpen]=useState(false),[pin,setPin]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const waiting=useRef<PinRequest[]>([]),previous=useRef<HTMLElement|null>(null),dialog=useRef<HTMLDivElement>(null),submitting=useRef(false);
 function finish(ok:boolean){const requests=waiting.current.splice(0);setOpen(false);setPin("");requests.forEach(r=>r.complete(ok));previous.current?.focus()}
 useEffect(()=>{const listener=(event:Event)=>{if(!waiting.current.length){previous.current=document.activeElement as HTMLElement;setPin("");setError("")}waiting.current.push((event as CustomEvent<PinRequest>).detail);setOpen(true)};window.addEventListener("groompro:request-pin",listener);return()=>{window.removeEventListener("groompro:request-pin",listener);waiting.current.splice(0).forEach(r=>r.complete(false))}},[]);
 async function submit(){if(submitting.current)return;if(!/^\d{4,10}$/.test(pin)){setError("Enter your 4–10 digit PIN.");return}submitting.current=true;setBusy(true);setError("");try{const r=await fetch("/api/employee/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin})});const d=await r.json();if(!r.ok){setError(d.error||"PIN not recognized.");return}onSignedIn(d.employee);finish(true)}catch{setError("Sign-in could not complete. Try again.")}finally{submitting.current=false;setBusy(false)}}
 if(!open)return null;
 return <div className="gp-modal-backdrop gp-action-pin" onKeyDown={e=>{if(e.key==="Escape"&&!busy)finish(false);if(e.key==="Tab"){const items=dialog.current?.querySelectorAll<HTMLElement>("input,button:not(:disabled)");if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><div ref={dialog} className="gp-pin-window" role="dialog" aria-modal="true" aria-labelledby="action-pin-title"><h2 id="action-pin-title">Employee PIN</h2><p>Enter your PIN to finish this action.</p><form onSubmit={e=>{e.preventDefault();submit()}}><input aria-label="Employee PIN" autoFocus autoComplete="off" type="password" inputMode="numeric" maxLength={10} className="gp-search-input" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))}/>{error&&<p role="alert" className="gp-form-error">{error}</p>}<div className="gp-modal-actions"><button type="button" className="gp-btn" disabled={busy} onClick={()=>finish(false)}>Cancel</button><button className="gp-btn primary" disabled={busy}>{busy?"Signing in…":"Continue"}</button></div></form></div></div>;
}

