"use client";
import {useEffect,useState} from "react";
import {employeeFetch} from "../lib/employee-fetch";
import {CatalogKind} from "../lib/catalog-input";
const titles={services:"Services",products:"Products",packages:"Packages",plans:"VIP Memberships"};
const blank=()=>({id:"",name:"",description:"",price:"",durationMin:"30",category:"",commissionPct:"",sku:"",quantity:"0",cost:"0",active:true,items:[] as {serviceId:string;quantity:number}[]});
export function CatalogWorkspace({kind}:{kind:CatalogKind}){
 const[data,setData]=useState<Record<CatalogKind,any[]>>({services:[],products:[],packages:[],plans:[]}),[form,setForm]=useState<ReturnType<typeof blank>|null>(null),[query,setQuery]=useState(""),[inactive,setInactive]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/catalog",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:"Catalog could not load.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);useEffect(()=>{setForm(null);setQuery("");setError("");setNotice("")},[kind]);
 function edit(item:any){setError("");setNotice("");setForm({...blank(),...item,description:item.description||"",category:item.category||"",sku:item.sku||"",price:(item.priceCents/100).toFixed(2),cost:((item.costCents||0)/100).toFixed(2),quantity:String(item.quantity||0),durationMin:String(item.durationMin||30),commissionPct:item.commissionPct==null?"":String(item.commissionPct),items:(item.items||[]).map((i:any)=>({serviceId:i.serviceId,quantity:i.quantity}))})}
 async function save(){if(!form||busy)return;setBusy(true);setError("");setNotice("");try{const dollars=(v:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(v.trim()))throw new Error("Enter prices in dollars, with no more than two decimal places.");return Math.round(Number(v)*100)};const body={...form,kind,priceCents:dollars(form.price),costCents:kind==="products"?dollars(form.cost):0,durationMin:Number(form.durationMin),quantity:Number(form.quantity),commissionPct:form.commissionPct===""?null:Number(form.commissionPct)};const r=await employeeFetch("/api/catalog",{method:form.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed.");setNotice(`${form.name} saved.`);setForm(null);await load()}catch(e){setError(e instanceof Error?e.message:"Save failed.")}finally{setBusy(false)}}
 const items=data[kind].filter(x=>(inactive||x.active)&&`${x.name} ${x.category||""} ${x.sku||""}`.toLowerCase().includes(query.toLowerCase()));
 const field=(label:string,key:keyof ReturnType<typeof blank>,type="text")=><label className="gp-field"><span className="gp-label">{label}</span><input required={["name","price","durationMin","quantity","cost"].includes(key)} min={type==="number"?0:undefined} step={type==="number"?1:undefined} type={type} className="gp-search-input" value={String(form?.[key]??"")} onChange={e=>setForm(f=>f?{...f,[key]:e.target.value}:f)}/></label>;
 return <section className="gp-settings"><div className="gp-calendar-head"><div><h1 className="gp-title">{titles[kind]}</h1><p className="gp-subtitle">{kind==="services"?"Create grooming services, prices, and appointment lengths.":kind==="products"?"Manage retail products, prices, and stock.":kind==="packages"?"Manage service bundles and their base prices.":"Manage VIP plans and customer memberships."}</p></div><button className="gp-btn primary" disabled={busy} onClick={()=>{setForm(blank());setError("");setNotice("")}}>+ Add {kind==="plans"?"VIP Plan":kind.slice(0,-1)}</button></div>{notice&&<div role="status" className="gp-form-success">{notice}</div>}{error&&<div role="alert" className="gp-form-error">{error}</div>}
 {form&&<form className="gp-settings-card" style={{marginBottom:16}} onSubmit={e=>{e.preventDefault();save()}}><h2>{form.id?"Edit":"New"} {kind==="plans"?"VIP Plan":kind.slice(0,-1)}</h2><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><div className="gp-catalog-fields">{field("Name","name")}{field(kind==="plans"?"Price per billing ($)":"Price ($)","price")}{kind==="services"&&<>{field("Duration (minutes)","durationMin","number")}{field("Category","category")}{field("Commission (%)","commissionPct")}</>}{kind==="products"&&<>{field("SKU","sku")}{field("Stock quantity","quantity","number")}{field("Unit cost ($)","cost")}</>}</div><label className="gp-field"><span className="gp-label">{kind==="plans"?"Plan benefits / description":"Description"}</span><textarea className="gp-search-input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{kind==="packages"&&<div className="gp-field"><strong>Included services</strong>{data.services.map(s=>{const item=form.items.find(i=>i.serviceId===s.id);return <label key={s.id} className="gp-radio-row"><input type="checkbox" checked={!!item} onChange={e=>setForm({...form,items:e.target.checked?[...form.items,{serviceId:s.id,quantity:1}]:form.items.filter(i=>i.serviceId!==s.id)})}/>{s.name}{!s.active&&" (inactive)"}{item&&<input aria-label={`Quantity of ${s.name}`} type="number" min={1} max={1000} value={item.quantity} style={{width:70}} onChange={e=>setForm({...form,items:form.items.map(i=>i.serviceId===s.id?{...i,quantity:Number(e.target.value)}:i)})}/>}</label>})}{!data.services.length&&<p>Add services from the Services menu first.</p>}</div>}{kind==="plans"&&<p className="gp-subtitle">Plan changes apply to new enrollments. Existing memberships retain their agreed price. Enrollment uses the business’s configured VIP billing days and existing $1 start fee.</p>}<label className="gp-radio-row"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Active — available for new use</label><div className="gp-modal-actions"><button type="button" className="gp-btn" onClick={()=>setForm(null)}>Cancel</button><button className="gp-btn primary">{busy?"Saving…":"Save"}</button></div></fieldset></form>}
 <div className="gp-calendar-options"><input aria-label={`Search ${titles[kind]}`} className="gp-search-input" style={{marginLeft:0}} placeholder={`Search ${titles[kind].toLowerCase()}`} value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={inactive} onChange={e=>setInactive(e.target.checked)}/>Include inactive</label><button className="gp-btn" onClick={()=>{setError("");load()}}>Refresh</button></div>{loading?<p>Loading catalog…</p>:<div className="gp-list">{items.map(item=><button key={item.id} className="gp-customer-result" disabled={busy} onClick={()=>edit(item)} aria-label={`Edit ${item.name}`}><div><strong>{item.name}{!item.active&&" (inactive)"}</strong><span>{kind==="services"?`${item.durationMin} min · ${item.category||"Uncategorized"}`:kind==="products"?`${item.quantity} in stock · ${item.sku||"No SKU"}`:kind==="packages"?`${item.items.length} included services`:item.description||"VIP plan"}</span></div><strong>${(item.priceCents/100).toFixed(2)}{kind==="plans"?" / billing":""}</strong></button>)}{!items.length&&<p className="gp-profile-empty">No {titles[kind].toLowerCase()} found. Use Add above to create one.</p>}</div>}{kind==="plans"&&<MembershipEnrollment plans={data.plans.filter(p=>p.active)}/>}</section>;
}
function MembershipEnrollment({plans}:{plans:any[]}){
 const[q,setQ]=useState(""),[customers,setCustomers]=useState<any[]>([]),[customer,setCustomer]=useState<any>(null),[petId,setPetId]=useState(""),[planId,setPlanId]=useState(""),[memberships,setMemberships]=useState<any[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(q.length<2||customer){setCustomers([]);return}const controller=new AbortController();const timer=setTimeout(()=>fetch(`/api/customers/search?q=${encodeURIComponent(q)}`,{signal:controller.signal}).then(r=>r.json()).then(d=>setCustomers(d.customers||[])).catch(()=>{}),250);return()=>{clearTimeout(timer);controller.abort()}},[q,customer]);
 async function load(id:string){const r=await fetch(`/api/memberships?customerId=${encodeURIComponent(id)}`),d=await r.json();if(!r.ok)throw new Error(d.error);setMemberships(d.memberships||[])}
 async function choose(c:any){setCustomer(c);setQ(`${c.firstName} ${c.lastName}`);setPetId(c.pets?.[0]?.id||"");setError("");setMemberships([]);try{await load(c.id)}catch(e){setError(String(e))}}
 async function act(body:any,method="POST"){setBusy(true);setError("");try{const r=await employeeFetch("/api/memberships",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);await load(customer.id)}catch(e){setError(e instanceof Error?e.message:"Membership update failed.")}finally{setBusy(false)}}
 return <div className="gp-settings-card" style={{marginTop:24}}><h2>Customer memberships</h2><p>Find a customer to enroll a dog or manage an existing membership.</p><label className="gp-field"><span className="gp-label">Customer</span><input className="gp-search-input" value={q} onChange={e=>{setQ(e.target.value);setCustomer(null);setMemberships([])}} placeholder="Search customer or pet"/></label>{customers.map(c=><button className="gp-customer-result" key={c.id} onClick={()=>choose(c)}>{c.firstName} {c.lastName} · {c.pets?.map((p:any)=>p.name).join(", ")}</button>)}{error&&<div role="alert" className="gp-form-error">{error}</div>}{customer&&<><div className="gp-catalog-fields"><label className="gp-field"><span className="gp-label">Dog</span><select className="gp-search-input" value={petId} onChange={e=>setPetId(e.target.value)}><option value="">Select dog</option>{customer.pets?.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="gp-field"><span className="gp-label">VIP plan</span><select className="gp-search-input" value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Select plan</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · ${(p.priceCents/100).toFixed(2)} / billing</option>)}</select></label></div><p>Enrollment records the existing $1 start fee and schedules the plan price for the configured billing days. This screen does not charge a card.</p><button className="gp-btn primary" disabled={busy||!petId||!planId} onClick={()=>act({customerId:customer.id,petId,planId})}>Enroll dog</button>{memberships.map(m=><div className="gp-list-row" key={m.id}><div><strong>{m.name} · {customer.pets?.find((p:any)=>p.id===m.petId)?.name||"Dog"}</strong><span>{m.status.replaceAll("_"," ")} · ${(m.recurringPriceCents/100).toFixed(2)} / billing</span></div><div style={{flexDirection:"row"}}><button className="gp-btn" disabled={busy||m.status!=="ACTIVE"} onClick={()=>act({membershipId:m.id,action:"PAUSE"},"PATCH")}>Request pause</button><button className="gp-btn" disabled={busy||!["PAUSE_REQUESTED","PAUSED"].includes(m.status)} onClick={()=>act({membershipId:m.id,action:"RESUME"},"PATCH")}>Resume</button><button className="gp-btn" disabled={busy||["CANCELLED","CANCELLATION_REQUESTED"].includes(m.status)} onClick={()=>act({membershipId:m.id,action:"CANCEL"},"PATCH")}>Request cancellation</button></div></div>)}</>}</div>;
}

