"use client";
import { useEffect, useState } from "react";
import { CustomerProfile } from "@/src/components/customer-profile";
import { CustomerCreateWindow } from "@/src/components/customer-create-window";

type CustomerResult={id:string;firstName:string;lastName:string;email:string|null;phones:{number:string;isPrimary:boolean}[];pets:{name:string}[]};
type LocationAccess={id:string;name:string;assigned:boolean};

export function CustomersWorkspace({onCreateTicket}:{onCreateTicket:(customerId:string)=>void}){
 const[query,setQuery]=useState("");const[results,setResults]=useState<CustomerResult[]>([]);const[selectedId,setSelectedId]=useState<string|null>(null);const[showCreate,setShowCreate]=useState(false);const[searching,setSearching]=useState(false);const[locations,setLocations]=useState<LocationAccess[]>([]);const[accessOpen,setAccessOpen]=useState(false);const[accessSaving,setAccessSaving]=useState(false);const[accessError,setAccessError]=useState("");
 useEffect(()=>{const q=query.trim();if(q.length<2){setResults([]);setSearching(false);return}const controller=new AbortController();const timer=window.setTimeout(async()=>{setSearching(true);try{const r=await fetch(`/api/customers/search?q=${encodeURIComponent(q)}`,{signal:controller.signal});const d=r.ok?await r.json():{customers:[]};setResults(d.customers||[])}catch{}finally{setSearching(false)}},200);return()=>{clearTimeout(timer);controller.abort()}},[query]);
 async function openAccess(){if(!selectedId)return;setAccessOpen(true);setAccessError("");try{const r=await fetch(`/api/customers/location-access?customerId=${encodeURIComponent(selectedId)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load locations.");setLocations(d.locations||[])}catch(e){setAccessError(e instanceof Error?e.message:"Unable to load locations.")}}
 async function saveAccess(){if(!selectedId)return;setAccessSaving(true);setAccessError("");try{const r=await fetch("/api/customers/location-access",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId:selectedId,locationIds:locations.filter(l=>l.assigned).map(l=>l.id)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save location access.");setAccessOpen(false)}catch(e){setAccessError(e instanceof Error?e.message:"Unable to save location access.")}finally{setAccessSaving(false)}}
 return <><section className="gp-calendar"><div className="gp-calendar-head" style={{padding:24}}><div><h1 className="gp-title">Customers</h1><p className="gp-subtitle">Find a client by phone, name, email, or pet name.</p></div><div className="gp-actions"><button className="gp-btn primary" onClick={()=>setShowCreate(true)}>+ New Customer</button></div></div><div style={{padding:"0 24px 24px"}}><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Phone, customer name, email, or pet" className="gp-search-input"/>{query.trim().length<2?<div className="gp-search-empty">Start typing to search existing customers.</div>:searching?<div className="gp-search-empty">Searching customers…</div>:results.length?<div className="gp-search-results">{results.map(c=><button className="gp-customer-result" key={c.id} onClick={()=>setSelectedId(c.id)}><div><strong>{c.firstName} {c.lastName}</strong><span>{c.phones.find(p=>p.isPrimary)?.number||c.email||"Contact not set"}</span></div><div><span>{c.pets.map(p=>p.name).join(", ")||"No pets"}</span><b>Open</b></div></button>)}</div>:<div className="gp-search-empty">No matching customers found.</div>}</div></section>{selectedId&&<><CustomerProfile customerId={selectedId} onClose={()=>setSelectedId(null)} onNewAppointment={onCreateTicket} onCreateTicket={onCreateTicket}/><div className="gp-floating-window" style={{position:"fixed",right:24,bottom:24,zIndex:20,padding:12}}><button className="gp-btn" onClick={openAccess}>Location Access</button></div></>}{showCreate&&<CustomerCreateWindow onClose={()=>setShowCreate(false)} onCreated={id=>{setShowCreate(false);setSelectedId(id)}} onOpenExisting={id=>{setShowCreate(false);setSelectedId(id)}}/>}{accessOpen&&<div className="gp-modal-backdrop" role="dialog" aria-modal="true"><div className="gp-pin-window"><h2 style={{marginTop:0}}>Customer Location Access</h2><p className="gp-floating-subtitle">Choose which business locations can access this customer when Customer Sharing is set to selected locations.</p>{locations.map(l=><label key={l.id} style={{display:"flex",gap:10,alignItems:"center",padding:"10px 0"}}><input type="checkbox" checked={l.assigned} onChange={e=>setLocations(x=>x.map(v=>v.id===l.id?{...v,assigned:e.target.checked}:v))}/><span>{l.name}</span></label>)}{!locations.length&&!accessError&&<div className="gp-search-empty">No locations are configured yet.</div>}{accessError&&<div className="gp-form-error">{accessError}</div>}<div className="gp-modal-actions"><button className="gp-btn" onClick={()=>setAccessOpen(false)}>Cancel</button><button className="gp-btn primary" disabled={accessSaving} onClick={saveAccess}>{accessSaving?"Saving…":"Save Access"}</button></div></div></div>}</>}
