"use client";
import { useMemo,useState } from "react";
type MappingKey="firstName"|"lastName"|"email"|"phone"|"address"|"address2"|"city"|"state"|"postalCode"|"dog1Name"|"dog1Breed"|"dog2Name"|"dog2Breed"|"dog3Name"|"dog3Breed"|"dog4Name"|"dog4Breed"|"dog5Name"|"dog5Breed";
const fields:{key:MappingKey;label:string;description:string}[]=[{key:"firstName",label:"First Name",description:"Customer's first name"},{key:"lastName",label:"Last Name",description:"Customer's last name"},{key:"email",label:"Email",description:"Customer email address"},{key:"phone",label:"Phone",description:"Primary customer phone number"},{key:"address",label:"Address",description:"Street mailing address"},{key:"address2",label:"Address 2",description:"Apartment, suite, unit, or second address line"},{key:"city",label:"City",description:"City"},{key:"state",label:"State",description:"State or province"},{key:"postalCode",label:"ZIP / Postal Code",description:"ZIP or postal code"},...[1,2,3,4,5].flatMap(n=>[{key:`dog${n}Name` as MappingKey,label:`${n}${n===1?"st":n===2?"nd":n===3?"rd":"th"} Dog`,description:`Dog ${n} name`},{key:`dog${n}Breed` as MappingKey,label:`${n}${n===1?"st":n===2?"nd":n===3?"rd":"th"} Dog Breed`,description:`Breed for dog ${n}`}])];
const normalize=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function guess(header:string){const n=normalize(header);const exact=fields.find(f=>normalize(f.label)===n);if(exact)return exact.key;const aliases:Record<string,MappingKey>={firstname:"firstName",fname:"firstName",lastname:"lastName",lname:"lastName",emailaddress:"email",phone:"phone",phonenumber:"phone",mobile:"phone",address1:"address",street:"address",address2:"address2",zipcode:"postalCode",zip:"postalCode",postalcode:"postalCode",city:"city",state:"state",dogname:"dog1Name",dog1:"dog1Name",dog1name:"dog1Name",dog2:"dog2Name",dog2name:"dog2Name",dog3:"dog3Name",dog3name:"dog3Name",dog4:"dog4Name",dog4name:"dog4Name",dog5:"dog5Name",dog5name:"dog5Name"};return aliases[n]||""}
export function CustomerImport(){const[fileName,setFileName]=useState("");const[headers,setHeaders]=useState<string[]>([]);const[rows,setRows]=useState<Record<string,string>[]>([]);const[mapping,setMapping]=useState<Record<string,string>>({});const[result,setResult]=useState<any>(null);const[busy,setBusy]=useState(false);const mapped=Object.values(mapping);const missingName=!mapped.includes("firstName")&&!mapped.includes("lastName");const missingContact=!mapped.includes("phone")&&!mapped.includes("email");const invalid=missingName||missingContact;const requiredMissing=useMemo(()=>[missingName?"First Name or Last Name":null,missingContact?"Phone or Email":null].filter(Boolean) as string[],[missingName,missingContact]);
 async function loadFile(file:File){const raw=parseCsv(await file.text());if(!raw.length)return;const hs=raw[0].map(x=>x.trim());setHeaders(hs);setRows(raw.slice(1).map(r=>Object.fromEntries(hs.map((h,i)=>[h,r[i]||""]))));const guessed:Record<string,string>={};hs.forEach(h=>{const g=guess(h);if(g&&!Object.values(guessed).includes(g))guessed[h]=g});setMapping(guessed);setFileName(file.name);setResult(null)}
 async function submit(dryRun:boolean){if(invalid){setResult({error:`Map these required fields first: ${requiredMissing.join("; ")}.`});return}setBusy(true);try{const r=await fetch("/api/import/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows,mapping,dryRun})});setResult(await r.json())}catch{setResult({error:"Import could not be completed."})}finally{setBusy(false)}}
 return <section className="gp-settings-card gp-settings-wide"><div className="gp-settings-card-head"><div><h2>Import Client Data</h2><p>Upload a CSV, let GroomPro recognize familiar headers, then review every field before data enters the database.</p></div><label className="gp-btn primary">Choose CSV<input type="file" accept=".csv,text/csv" hidden onChange={e=>e.target.files?.[0]&&loadFile(e.target.files[0])}/></label></div>{fileName&&<><div className="gp-import-file"><strong>{fileName}</strong><span>{rows.length.toLocaleString()} client rows detected</span></div><div className="gp-import-help"><strong>Human-readable field names are intentional.</strong> A source header such as <code>Ab2</code> can be mapped to <strong>Address</strong>; <code>ID311</code> can be mapped to <strong>1st Dog</strong>. Technical database names remain hidden.</div><div className="gp-import-table"><div className="gp-import-row header"><span>Source table header</span><span>GroomPro field</span><span>What this field means</span></div>{headers.map(h=>{const key=mapping[h]||"";const f=fields.find(x=>x.key===key);return <div className="gp-import-row" key={h}><span><strong>{h}</strong></span><span><select value={key} onChange={e=>setMapping({...mapping,[h]:e.target.value})}><option value="">Do not import</option>{fields.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></span><span>{f?.description||"Choose the correct meaning for this source column."}</span></div>})}</div><div className="gp-modal-actions"><button className="gp-btn" disabled={busy} onClick={()=>submit(true)}>Preview Import</button><button className="gp-btn primary" disabled={busy||invalid} onClick={()=>submit(false)}>{busy?"Importing…":"Import Client Data"}</button></div>{invalid&&<div className="gp-form-error">Required mapping: {requiredMissing.join("; ")}.</div>}{result&&<pre className="gp-import-result">{JSON.stringify(result,null,2)}</pre>}</>}</section>;
}
