"use client";
import {useState} from 'react';
import {employeeFetch} from '../lib/employee-fetch';
import {CompensationRules,defaultCompensation} from '../lib/compensation-rules';
export function EmployeeCompensation({userId}:{userId:string}){
 const [data,setData]=useState<any>(null),[rules,setRules]=useState<CompensationRules>(defaultCompensation),[enabled,setEnabled]=useState(false),[hire,setHire]=useState(''),[dates,setDates]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 function apply(d:any){setData(d);setEnabled(!!d.rules);setRules(d.rules||defaultCompensation);setHire(d.dateOfHire?.slice(0,10)||'');setDates((d.workedDates||[]).join(', '))}
 async function request(action:string,approveQualification=false){setBusy(true);setMessage('');try{const response=await employeeFetch('/api/employees/compensation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,action,rules:enabled?rules:null,dateOfHire:hire,workedDates:dates.split(/[\s,]+/).filter(Boolean),approveQualification})});const result=await response.json();if(!response.ok)throw Error(result.error);apply(result);if(action!=='VIEW')setMessage('Compensation saved. Closed tickets keep their original earnings.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section style={{gridColumn:'1 / -1'}}><h3>Compensation</h3>{!data?<button type="button" className="gp-btn" disabled={busy} onClick={()=>void request('VIEW')}>Manage compensation</button>:<>
 <p>Last 30 calendar days ({data.from} through {data.through}): {data.metric.dogs} dogs / {data.metric.workedDays} worked days = <strong>{data.metric.average.toFixed(2)} dogs/day</strong>. Completed grooming assignments count once per dog per day. Add actual worked dates below to include days with no dogs.</p>
 <label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Use employee compensation rules</label>
 <div className="gp-staff-week-editor"><label>Hire date<input type="date" value={hire} onChange={e=>setHire(e.target.value)}/></label><label>Actual worked dates (YYYY-MM-DD, separated by commas)<textarea value={dates} onChange={e=>setDates(e.target.value)}/></label></div>
 {enabled&&<><div className="gp-staff-week-editor"><label>Hourly rate ($)<input type="number" min="0" step="0.01" value={rules.hourlyCents/100} onChange={e=>setRules({...rules,hourlyCents:Math.round(Number(e.target.value)*100)})}/></label><label>Base service commission (%)<input type="number" min="0" max="100" value={rules.basePercent} onChange={e=>setRules({...rules,basePercent:Number(e.target.value)})}/></label><label><input type="checkbox" checked={rules.participatesInTips} onChange={e=>setRules({...rules,participatesInTips:e.target.checked})}/> Participates in tips</label></div>
 <h4>Qualification thresholds</h4>{rules.tiers.map((tier,i)=><div className="gp-staff-week-editor" key={i}><label>Minimum dogs/day<input type="number" min="0" step="0.1" value={tier.minimumAverage} onChange={e=>setRules({...rules,tiers:rules.tiers.map((t,n)=>n===i?{...t,minimumAverage:Number(e.target.value)}:t)})}/></label><label>Minimum days employed<input type="number" min="0" value={tier.minimumDaysEmployed} onChange={e=>setRules({...rules,tiers:rules.tiers.map((t,n)=>n===i?{...t,minimumDaysEmployed:Number(e.target.value)}:t)})}/></label><label>Commission (%)<input type="number" min="0" max="100" value={tier.percent} onChange={e=>setRules({...rules,tiers:rules.tiers.map((t,n)=>n===i?{...t,percent:Number(e.target.value)}:t)})}/></label><button type="button" className="gp-btn" onClick={()=>setRules({...rules,tiers:rules.tiers.filter((_,n)=>n!==i)})}>Remove threshold</button></div>)}<button type="button" className="gp-btn" onClick={()=>setRules({...rules,tiers:[...rules.tiers,{minimumAverage:0,minimumDaysEmployed:0,percent:rules.basePercent}]})}>Add threshold</button>
 <h4>Specific earnings</h4><p>Match a service code, category, or workflow role (PREP, BATH, GROOM), or use * for all items in that scope. Specific matches take priority. Service exemptions always apply. VIP first-billing rules are earned only after a verified first recurring payment.</p>
 {rules.rules.map((rule,i)=><div className="gp-staff-week-editor" key={i}><label>Applies to<select value={rule.scope} onChange={e=>setRules({...rules,rules:rules.rules.map((r,n)=>n===i?{...r,scope:e.target.value as any}:r)})}><option value="SERVICE">Services</option><option value="PRODUCT">Merchandise</option><option value="PACKAGE">Packages</option><option value="VIP_FIRST_BILLING">VIP first recurring payment</option></select></label><label>Code / category / role<input value={rule.match} onChange={e=>setRules({...rules,rules:rules.rules.map((r,n)=>n===i?{...r,match:e.target.value}:r)})}/></label><label>Method<select value={rule.method} onChange={e=>setRules({...rules,rules:rules.rules.map((r,n)=>n===i?{...r,method:e.target.value as any,amount:0}:r)})}><option value="PERCENT">Percent</option><option value="PER_DOG">Dollars per dog</option><option value="PER_UNIT">Dollars per unit</option></select></label><label>{rule.method==='PERCENT'?'Percent':'Dollars'}<input type="number" min="0" step="0.01" value={rule.method==='PERCENT'?rule.amount:rule.amount/100} onChange={e=>setRules({...rules,rules:rules.rules.map((r,n)=>n===i?{...r,amount:rule.method==='PERCENT'?Number(e.target.value):Math.round(Number(e.target.value)*100)}:r)})}/></label><button type="button" className="gp-btn" onClick={()=>setRules({...rules,rules:rules.rules.filter((_,n)=>n!==i)})}>Remove rule</button></div>)}<button type="button" className="gp-btn" onClick={()=>setRules({...rules,rules:[...rules.rules,{scope:'SERVICE',match:'*',method:'PERCENT',amount:0}]})}>Add earnings rule</button></>}
 {data.qualification&&<p>Qualified rate: {data.qualification.qualifiedPercent}%. Applied rate: {data.qualification.appliedPercent}%. {data.qualification.approvalPending&&'Manager approval is pending.'}</p>}
 <div className="gp-modal-actions"><button type="button" className="gp-btn primary" disabled={busy} onClick={()=>void request('SAVE')}>Save compensation</button>{data.qualification?.approvalPending&&<button type="button" className="gp-btn" disabled={busy} onClick={()=>void request('SAVE',true)}>Approve qualified rate</button>}</div></>}{message&&<p role="status">{message}</p>}</section>;
}
