"use client";
import {useEffect,useState} from "react";
import {employeeFetch} from "../lib/employee-fetch";
import {DayHours} from "../lib/operating-hours";
const names=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export function OperatingHoursSettings({locationId}:{locationId:string}){
 const[hours,setHours]=useState<DayHours[]>([]),[zone,setZone]=useState("America/Chicago"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{setHours([]);setMessage("");setError("");if(!locationId)return;const c=new AbortController();fetch(`/api/operating-hours?locationId=${encodeURIComponent(locationId)}`,{signal:c.signal,cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setHours(d.hours);setZone(d.timezone)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[locationId]);
 async function save(){setBusy(true);setMessage("");setError("");try{const r=await employeeFetch("/api/operating-hours",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({locationId,timezone:zone,hours})}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessage("Operating hours saved. New bookings and appointment changes must fit these hours.")}catch(e){setError(e instanceof Error?e.message:"Unable to save hours.")}finally{setBusy(false)}}
 return <div className="gp-settings-card"><h2>Location operating hours</h2><p>Applies to the location selected under Locations. Appointments must start and finish within these hours. Existing bookings stay in place when hours change.</p>{!locationId?<p>Select a location first.</p>:<><label className="gp-field"><span className="gp-label">Time zone</span><input className="gp-search-input" list="gp-timezones" value={zone} onChange={e=>setZone(e.target.value)} disabled={busy}/><datalist id="gp-timezones">{["America/Chicago","America/New_York","America/Denver","America/Phoenix","America/Los_Angeles","America/Anchorage","Pacific/Honolulu","UTC"].map(z=><option key={z} value={z}/>)}</datalist></label>{hours.map(h=><div key={h.day} style={{display:"grid",gridTemplateColumns:"90px 80px 1fr 1fr",gap:8,alignItems:"center",marginBottom:8}}><strong>{names[h.day]}</strong><label><input type="checkbox" checked={h.closed} disabled={busy} onChange={e=>setHours(x=>x.map(d=>d.day===h.day?{...d,closed:e.target.checked}:d))}/>Closed</label>{(["open","close"] as const).map(key=><input key={key} aria-label={`${names[h.day]} ${key}`} type="time" value={h[key]} disabled={busy||h.closed} onChange={e=>setHours(x=>x.map(d=>d.day===h.day?{...d,[key]:e.target.value}:d))}/>)}</div>)}<button className="gp-btn primary" disabled={busy||hours.length!==7} onClick={save}>{busy?"Saving…":"Save hours"}</button></>}{error&&<div role="alert" className="gp-form-error">{error}</div>}{message&&<div role="status" className="gp-form-success">{message}</div>}</div>;
}

