"use client";
import {useState} from 'react';
import {employeeFetch} from '@/src/lib/employee-fetch';
export type PetRecord={id:string;customerId:string;name:string;breed:string|null;notes:string|null;vaccinations?:{id:string;vaccineName:string;expiresAt:string|null}[]};
export function PetEditor({pet,customerId,ownerName,onSaved,onCancel}:{pet?:PetRecord;customerId:string;ownerName:string;onSaved:(pet:PetRecord)=>void;onCancel:()=>void}){
 const[form,setForm]=useState({name:pet?.name||'',breed:pet?.breed||'',notes:pet?.notes||''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){setBusy(true);setError('');try{const r=await employeeFetch('/api/pets',{method:pet?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,id:pet?.id,customerId})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save pet.');onSaved(d.pet)}catch(e){setError(e instanceof Error?e.message:'Could not save pet.')}finally{setBusy(false)}}
 return <form className="gp-settings-card" onSubmit={e=>{e.preventDefault();void save()}}><h3>{pet?'Edit pet':'Add pet'}</h3><p>Owner: <strong>{ownerName}</strong></p>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy} className="gp-staff-week-editor"><label>Pet name<input autoFocus required maxLength={191} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Breed<input maxLength={191} value={form.breed} onChange={e=>setForm({...form,breed:e.target.value})}/></label><label>Pet notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="gp-btn primary">{busy?'Saving…':'Save pet'}</button><button type="button" className="gp-btn" onClick={onCancel}>Cancel</button></fieldset>{pet?.vaccinations?.length?<div><h4>Vaccinations</h4>{pet.vaccinations.map(v=><p key={v.id}>{v.vaccineName}{v.expiresAt?` — expires ${v.expiresAt.slice(0,10)}`:''}</p>)}</div>:null}</form>
}
