"use client";
import {createContext,useContext,useEffect,useRef,useState} from 'react';
type Geometry={left:number;top:number;width:number;height:number};let saved:Geometry|null=null;let savedFull=false;
const WindowContext=createContext({full:false,toggle:()=>{}});
export function PosFullSizeButton(){const ctx=useContext(WindowContext);return <button className="gp-btn" onClick={ctx.toggle}>{ctx.full?'Restore Size':'Full Size'}</button>}
export function PosWindowFrame({children}:{children:React.ReactNode}){
 const root=useRef<HTMLDivElement>(null),drag=useRef<(Geometry&{x:number;y:number;resize:boolean})|null>(null);const[full,setFull]=useState(false);
 const geometry=()=>{const b=root.current!.getBoundingClientRect();return{left:b.left,top:b.top,width:b.width,height:b.height}};
 function apply(g:Geometry){const el=root.current;if(!el)return;el.style.left=Math.max(0,Math.min(g.left,window.innerWidth-100))+'px';el.style.top=Math.max(0,Math.min(g.top,window.innerHeight-45))+'px';el.style.width=Math.min(g.width,window.innerWidth-16)+'px';el.style.height=Math.min(g.height,window.innerHeight-16)+'px';el.style.right='auto';el.style.bottom='auto';el.style.margin='0'}
 useEffect(()=>{if(saved)apply(saved);if(savedFull){apply({left:8,top:8,width:window.innerWidth-16,height:window.innerHeight-16});setFull(true)}return()=>{}},[]);
 function toggle(){if(!full){saved=geometry();apply({left:8,top:8,width:window.innerWidth-16,height:window.innerHeight-16})}else if(saved)apply(saved);savedFull=!full;setFull(!full)}
 return <WindowContext.Provider value={{full,toggle}}><div ref={root} className="gp-floating-window gp-ticket-window gp-pos-window gp-pos-adjustable" role="dialog" aria-label="POS Ticket" style={{resize:'none'}} onPointerDown={e=>{if(full)return;const target=e.target as HTMLElement,resize=!!target.closest('[data-pos-resize]');if(!resize&&(!target.closest('.gp-floating-head')||target.closest('button,input,select,textarea')))return;e.preventDefault();drag.current={...geometry(),x:e.clientX,y:e.clientY,resize};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d)return;if(d.resize)apply({...d,width:Math.max(Math.min(650,window.innerWidth-16),d.width+e.clientX-d.x),height:Math.max(400,d.height+e.clientY-d.y)});else apply({...d,left:d.left+e.clientX-d.x,top:d.top+e.clientY-d.y})}} onPointerUp={e=>{if(drag.current)saved=geometry();drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>{if(drag.current)saved=geometry();drag.current=null}}>{children}{!full&&<span data-pos-resize="true" className="gp-pos-resize" title="Drag to resize POS Ticket" aria-hidden="true">◢</span>}</div></WindowContext.Provider>
}
