"use client";
import {PosWindowFrame} from './pos-window-frame';
import {PosItems} from './pos-items';
import {CustomerProfile} from './customer-profile';
import {MembershipEnrollment} from './catalog-workspace';
import {localToInstant,wallTime} from "../lib/operating-hours";
import {employeeFetch} from "../lib/employee-fetch";
import { useEffect, useState } from "react";
type Employee={id:string;firstName:string;lastName:string;role:string};
type Account={balanceCents:number;creditCents:number;loyaltyPoints:number};
type Reward={id:string;name:string;description:string|null;rewardType:string;pointsCost:number;discountCents:number|null;secret:boolean};
type TicketDetail={createdAt?:string;pickupAt?:string|null;pickupCompletedAt?:string|null;daycareStatus?:string;id:string;orderNumber:number;status:string;scheduledStart:string|null;notes:string|null;checkedInAt?:string|null;arrivalPriority?:number|null;customer:{id:string;firstName:string;lastName:string;email:string|null;phones:{number:string;isPrimary:boolean}[]};pets:{pet:{name:string;breed:string|null};vipAvailability:string|null}[];lines:{description:string;quantity:number;unitPriceCents?:number;totalCents?:number;discountCents?:number;pet:{name:string}|null;role?:string}[];assignments:{role:string;user:{firstName:string;lastName:string}}[];scheduleHistory:{changeType:string;previousStart:string|null;newStart:string;changedAt:string;actor:{firstName:string;lastName:string}|null}[]};
type Checkout={subtotalCents:number;tipCents:number;salesTaxCents:number;totalCents:number;paidCents:number;dueCents:number;account?:Account};
const statuses=["OPEN","CONFIRMED","CHECKED_IN","IN_PROGRESS","READY","NO_SHOW","CLOSED","CANCELLED"];
const money=(c:number)=>`$${(c/100).toFixed(2)}`;
function localInput(date:Date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}T${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`}
export function PosTicketRecord({ticketId:initialTicketId,onClose,date,initialCustomerId,onSaved}:{ticketId?:string;onClose:()=>void;date?:Date;initialCustomerId?:string|null;onSaved?:(id:string)=>void}){
 const[ticketId,setTicketId]=useState(initialTicketId||'');
 const[catalog,setCatalog]=useState<any>({services:[],products:[],packages:[],plans:[]}),[employees,setEmployees]=useState<any[]>([]),[busy,setBusy]=useState(false),[hoursReady,setHoursReady]=useState(false),[customerQuery,setCustomerQuery]=useState(''),[customerResults,setCustomerResults]=useState<any[]>([]),[choosingCustomer,setChoosingCustomer]=useState(!initialCustomerId&&!initialTicketId),[ownerView,setOwnerView]=useState<{id:string;petId?:string}|null>(null),[pendingOwner,setPendingOwner]=useState<any>(null),[replacementPet,setReplacementPet]=useState(''),[customerPets,setCustomerPets]=useState<any[]>([]),[bookingWarning,setBookingWarning]=useState(false);
 const emptyTicket=()=>({id:'',status:'OPEN',customer:{id:'',firstName:'',lastName:'',phones:[]},pets:[],lines:[],assignments:[],scheduleHistory:[],notes:'',scheduledStart:null});
 const[panel,setPanel]=useState("Items");
 const[timezone,setTimezone]=useState("America/Chicago");
 const[ticket,setTicket]=useState<any>(initialTicketId?null:emptyTicket()),[account,setAccount]=useState<Account>({balanceCents:0,creditCents:0,loyaltyPoints:0}),[rewards,setRewards]=useState<Reward[]>([]),[cardOnFile,setCardOnFile]=useState(false),[error,setError]=useState(""),[moving,setMoving]=useState(false),[statusSaving,setStatusSaving]=useState(false),[rebooking,setRebooking]=useState(false),[rebookStart,setRebookStart]=useState(""),[groomers,setGroomers]=useState<Employee[]>([]),[groomerId,setGroomerId]=useState(""),[confirmWarning,setConfirmWarning]=useState(false),[newStart,setNewStart]=useState(()=>{const d=new Date(date||new Date());d.setHours(9,0,0,0);return localInput(d)}),[checkout,setCheckout]=useState<Checkout|null>(null),[tip,setTip]=useState("0"),[tax,setTax]=useState("0"),[paymentType,setPaymentType]=useState("CASH"),[paymentAmount,setPaymentAmount]=useState(""),[paying,setPaying]=useState(false),[closing,setClosing]=useState(false),[accountType,setAccountType]=useState("CREDIT"),[accountAmount,setAccountAmount]=useState(""),[accountReason,setAccountReason]=useState(""),[adjusting,setAdjusting]=useState(false),[noShowing,setNoShowing]=useState(false),[redeeming,setRedeeming]=useState("");
 async function load(id=ticketId){if(!id)return;try{const r=await employeeFetch(`/api/tickets/${id}`),d=await r.json();if(!r.ok)throw new Error(d.error||"Ticket could not be loaded.");setTicket(d.ticket);setCustomerPets(d.ticket.pets.map((p:any)=>p.pet));setTimezone(d.ticket.location?.timezone||"America/Chicago");setAccount(d.account||{balanceCents:0,creditCents:0,loyaltyPoints:0});setRewards(d.rewards||[]);setCardOnFile((d.paymentMethods||[]).length>0);if(d.ticket.scheduledStart){const x=new Date(d.ticket.scheduledStart);setNewStart(wallTime(x,d.ticket.location?.timezone||"America/Chicago"));setRebookStart(wallTime(x,d.ticket.location?.timezone||"America/Chicago"))}}catch(e){setError(e instanceof Error?e.message:"Ticket could not be loaded.")}}
 async function loadGroomers(){try{const r=await employeeFetch("/api/employees");if(r.ok){const d=await r.json();setGroomers((d.employees||[]).filter((e:Employee)=>["GROOMER","MASTER_GROOMER"].includes(e.role)))}}catch{}}
 async function loadCheckout(id=ticketId){if(!id)return;try{const r=await employeeFetch(`/api/tickets/checkout?ticketId=${id}`);if(r.ok){const d=await r.json();setCheckout(d);setAccount(d.account||account);setTip(String(d.tipCents||0));setTax(String(d.salesTaxCents||0));if(!paymentAmount&&d.dueCents>0)setPaymentAmount(String(d.dueCents))}}catch{}}
 useEffect(()=>{if(ticketId){load();loadCheckout()}loadGroomers()},[ticketId]);
 useEffect(()=>{Promise.all([employeeFetch('/api/catalog'),employeeFetch('/api/employees'),employeeFetch('/api/operating-hours')]).then(async rs=>{const [c,e,h]=await Promise.all(rs.map(r=>r.json()));if(rs.some(r=>!r.ok))throw Error('Ticket options could not load.');setCatalog(c);setEmployees(e.employees||[]);if(!initialTicketId)setTimezone(h.timezone);setHoursReady(true)}).catch(e=>setError(e.message));if(initialCustomerId&&!initialTicketId)employeeFetch(`/api/customers/${initialCustomerId}`).then(r=>r.json()).then(d=>chooseCustomer(d.customer)).catch(()=>setError('Customer could not load.'))},[]);
 useEffect(()=>{if(!choosingCustomer||customerQuery.trim().length<2){setCustomerResults([]);return}const c=new AbortController();const timer=setTimeout(()=>employeeFetch(`/api/customers/search?q=${encodeURIComponent(customerQuery)}`,{signal:c.signal}).then(r=>r.json()).then(d=>setCustomerResults(d.customers||[])).catch(()=>{}),200);return()=>{clearTimeout(timer);c.abort()}},[customerQuery,choosingCustomer]);
 useEffect(()=>{const refresh=()=>{if(ticketId){load();loadCheckout()}};window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh)},[ticketId]);
 async function chooseCustomer(c:any){if(!c)return;if(ticketId){setPendingOwner(c);setReplacementPet(c.pets?.[0]?.id||'');return}setTicket((t:any)=>({...t,customer:c,pets:c.pets?.[0]?[{pet:c.pets[0]}]:[],lines:t.lines.map((l:any)=>({...l,petId:l.type==='PRODUCT'?undefined:c.pets?.[0]?.id}))}));setCustomerPets(c.pets||[]);setChoosingCustomer(false);setCustomerQuery('');try{const [a,r]=await Promise.all([employeeFetch(`/api/customers/account?customerId=${c.id}`).then(r=>r.json()),employeeFetch(`/api/customers/rewards?customerId=${c.id}`).then(r=>r.json())]);setAccount(a.customer||{balanceCents:0,creditCents:0,loyaltyPoints:0});setRewards(r.catalog||[])}catch{setError('Customer account could not load.')}}
 async function changeCustomer(){setBusy(true);setError('');try{const r=await employeeFetch('/api/tickets/customer',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticketId,customerId:pendingOwner.id,petId:replacementPet})}),d=await r.json();if(!r.ok)throw Error(d.error);setPendingOwner(null);setChoosingCustomer(false);await load();await loadCheckout()}catch(e){setError(e instanceof Error?e.message:'Customer could not change.')}finally{setBusy(false)}}
 async function saveTicket(confirmConflict=false){if(ticketId)return ticketId;if(!hoursReady||!ticket.customer.id||!ticket.lines.length){setError('Choose a customer and at least one item before saving.');return ''}setBusy(true);setError('');try{const r=await employeeFetch('/api/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:ticket.customer.id,petIds:ticket.pets.map((p:any)=>p.pet.id),lines:ticket.lines,scheduledStart:localToInstant(newStart,timezone).toISOString(),notes:ticket.notes,groomerId:groomerId||undefined,arrivalPriority:ticket.arrivalPriority||undefined,confirmRecentWarning:confirmConflict})}),d=await r.json();if(!r.ok){if(d.requiresConfirmation)setBookingWarning(true);throw Error(d.error||d.warning||'Ticket could not save.')}setBookingWarning(false);setTicketId(d.ticket.id);onSaved?.(d.ticket.id);return d.ticket.id}catch(e){setError(e instanceof Error?e.message:'Ticket could not save.');return ''}finally{setBusy(false)}}
 async function itemAction(action:'add'|'edit'|'remove',value:any,index=0){
 if(!ticketId){setTicket((t:any)=>({...t,lines:action==='add'?[...t.lines,value]:action==='remove'?t.lines.filter((_:any,i:number)=>i!==index):t.lines.map((l:any,i:number)=>i===index?{...l,...value,totalCents:(l.unitPriceCents||0)*(value.quantity??l.quantity)}:l)}));return}
 setBusy(true);setError('');try{const line=ticket.lines[index];const url=action==='remove'?`/api/ticket-lines?lineId=${line.id}`:'/api/ticket-lines';const r=await employeeFetch(url,{method:action==='add'?'POST':action==='edit'?'PATCH':'DELETE',headers:{'Content-Type':'application/json'},...(action!=='remove'?{body:JSON.stringify(action==='add'?{...value,ticketId}:{...value,lineId:line.id})}:{})}),d=await r.json();if(!r.ok)throw Error(d.error);await load();await loadCheckout()}catch(e){setError(e instanceof Error?e.message:'Items could not update.')}finally{setBusy(false)}}
 async function closeOwner(){setOwnerView(null);if(ticketId){await load();return}if(ticket.customer.id){const r=await employeeFetch(`/api/customers/${ticket.customer.id}`),d=await r.json();if(r.ok){setCustomerPets(d.customer.pets);setTicket((t:any)=>({...t,customer:d.customer,pets:t.pets.map((p:any)=>({pet:d.customer.pets.find((v:any)=>v.id===p.pet.id)||p.pet}))}))}}}

 async function move(){if(!newStart)return;setMoving(true);setError("");try{const r=await employeeFetch("/api/tickets",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId,scheduledStart:localToInstant(newStart,timezone).toISOString()})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Appointment could not be moved.");await load()}catch(e){setError(e instanceof Error?e.message:"Appointment could not be moved.")}finally{setMoving(false)}}
 async function changeStatus(next:string){if(!ticket||next===ticket.status)return;setStatusSaving(true);setError("");try{const r=await employeeFetch("/api/tickets/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId,status:next})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Ticket status could not be changed.");await load();await loadCheckout()}catch(e){setError(e instanceof Error?e.message:"Ticket status could not be changed.")}finally{setStatusSaving(false)}}
 async function checkIn(){await changeStatus("CHECKED_IN")}
 function chooseWeeks(weeks:number){if(!ticket?.scheduledStart)return;const d=new Date(wallTime(new Date(ticket.scheduledStart),timezone));d.setDate(d.getDate()+weeks*7);setRebookStart(localInput(d))}
 async function rebook(){if(!rebookStart||!ticket)return;setRebooking(true);setError("");try{const r=await employeeFetch("/api/tickets/rebook",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId,scheduledStart:localToInstant(rebookStart,timezone).toISOString(),groomerId:groomerId||null,confirmRecentWarning:confirmWarning})}),d=await r.json();if(!r.ok){if(d.requiresConfirmation){setConfirmWarning(true);throw new Error(d.error||"Please confirm the nearby appointment warning.")}throw new Error(d.error||"Appointment could not be rebooked.")}setConfirmWarning(false);await load()}catch(e){setError(e instanceof Error?e.message:"Appointment could not be rebooked.")}finally{setRebooking(false)}}
 async function recordPayment(){const amountCents=Math.round(Number(paymentAmount)),tipCents=Math.max(0,Math.round(Number(tip))),salesTaxCents=Math.max(0,Math.round(Number(tax)));setPaying(true);setError("");try{const r=await employeeFetch("/api/tickets/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId,action:"PAYMENT",paymentType,amountCents,tipCents,salesTaxCents})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Payment could not be recorded.");setCheckout(d);setAccount(d.account||account);setPaymentAmount(String(d.dueCents||""));await load()}catch(e){setError(e instanceof Error?e.message:"Payment could not be recorded.")}finally{setPaying(false)}}
 async function closeTicket(){setClosing(true);setError("");try{const r=await employeeFetch("/api/tickets/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId,action:"CLOSE",tipCents:Number(tip)||0,salesTaxCents:Number(tax)||0})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Ticket cannot be closed.");setCheckout(d);await load()}catch(e){setError(e instanceof Error?e.message:"Ticket cannot be closed.")}finally{setClosing(false)}}
 async function processNoShow(){setNoShowing(true);setError("");try{const r=await employeeFetch("/api/tickets/no-show",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId})}),d=await r.json();if(!r.ok)throw new Error(d.error||"No-Show fee could not be processed.");await load();await loadCheckout()}catch(e){setError(e instanceof Error?e.message:"No-Show fee could not be processed.")}finally{setNoShowing(false)}}
 async function adjustAccount(){const cents=Math.round(Number(accountAmount));if(!cents||!accountReason.trim())return;setAdjusting(true);setError("");try{const r=await employeeFetch("/api/customers/account",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId:ticket?.customer.id,entryType:accountType,amountCents:cents,reason:accountReason})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Account adjustment failed.");setAccount(d.customer);setAccountAmount("");setAccountReason("");await load();await loadCheckout()}catch(e){setError(e instanceof Error?e.message:"Account adjustment failed.")}finally{setAdjusting(false)}}
 async function redeemReward(reward:Reward){const id=ticketId||await saveTicket();if(!id)return;setRedeeming(reward.id);setError("");try{const r=await employeeFetch("/api/customers/rewards",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REDEEM",customerId:ticket?.customer.id,ticketId:id,rewardId:reward.id})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Reward could not be redeemed.");await load(id);await loadCheckout(id)}catch(e){setError(e instanceof Error?e.message:"Reward could not be redeemed.")}finally{setRedeeming("")}}

 const stamp=(value?:string|null)=>value?new Date(value).toLocaleString(undefined,{timeZone:timezone,month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}):"—";
 const terminal=!!ticket&&["CLOSED","CANCELLED","NO_SHOW"].includes(ticket.status);
 return <><PosWindowFrame>
 <div className="gp-floating-head"><div className="gp-floating-title">POS Ticket {ticket?.orderNumber?`#${ticket.orderNumber}`:""} <small>{ticket?.customer.firstName} {ticket?.customer.lastName}</small></div><small>Drag title bar to move · Drag bottom-right corner to resize</small><button className="gp-btn" onClick={onClose}>Close</button></div>
 {error&&<div role="alert" className="gp-form-error">{error}</div>}
 {!ticket?<div className="gp-search-empty">{error?"Ticket unavailable":"Loading ticket…"}</div>:<>
 <header className="gp-pos-header">
 <section className="gp-pos-card"><h2>Ticket information</h2><div className="gp-pos-inline"><strong>{ticket.orderNumber?`#${ticket.orderNumber}`:"Unsaved"}</strong><label>Status <select aria-label="Ticket status" value={ticket.status} disabled={!ticketId||statusSaving||terminal||busy} onChange={e=>e.target.value==="CLOSED"?closeTicket():e.target.value==="NO_SHOW"?processNoShow():changeStatus(e.target.value)}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label></div><small>Created {stamp(ticket.createdAt)}</small><div className="gp-field"><span className="gp-label">Appointment date / time</span><div style={{display:"flex",gap:8}}><input className="gp-search-input" aria-label="Appointment date and time" type="datetime-local" value={newStart} onBlur={e=>setNewStart(e.currentTarget.value)} onChange={e=>setNewStart(e.target.value)}/><button className="gp-btn primary" disabled={busy||moving||!newStart} onClick={()=>ticketId?move():saveTicket()}>{busy?"Saving…":moving?"Moving…":ticketId?"Move":"Save / Schedule"}</button></div><small>Every move is recorded in Ticket History with the employee responsible.</small></div></section>
 <section className="gp-pos-card"><h2>Visit progress</h2><label className="gp-pos-progress"><input type="checkbox" checked={!!ticket.checkedInAt} disabled={!ticketId||terminal||statusSaving||!!ticket.checkedInAt} onChange={checkIn}/> Checked in <time>{stamp(ticket.checkedInAt)}</time></label><label className="gp-pos-progress"><input type="checkbox" checked={!!ticket.pickupAt} disabled={!ticketId||terminal||statusSaving||!!ticket.pickupAt} onChange={()=>changeStatus("READY")}/> Ready for pickup <time>{stamp(ticket.pickupAt)}</time></label><label className="gp-pos-progress"><input type="checkbox" checked={!!ticket.pickupCompletedAt} disabled readOnly/> Pickup completed <time>{stamp(ticket.pickupCompletedAt)}</time></label><small>Pickup completion is recorded by Check Out / Close.</small><div>Arrival order {ticketId?<strong>{ticket.arrivalPriority||"—"}</strong>:<input type="number" min={1} aria-label="Arrival priority" value={ticket.arrivalPriority||""} onChange={e=>setTicket({...ticket,arrivalPriority:Number(e.target.value)||null})}/>}</div>{!ticketId&&<label>Scheduled groomer<select value={groomerId} onChange={e=>setGroomerId(e.target.value)}><option value="">Assign later</option>{groomers.map(g=><option key={g.id} value={g.id}>{g.firstName} {g.lastName}</option>)}</select></label>}</section>
 <section className="gp-pos-card"><h2>Customer & dogs</h2><strong>{ticket.customer.firstName} {ticket.customer.lastName}</strong><div><button className="gp-btn" disabled={!ticket.customer.id} onClick={()=>setOwnerView({id:ticket.customer.id})}>Edit customer</button><button className="gp-btn" disabled={busy||terminal} onClick={()=>setChoosingCustomer(v=>!v)}>Change customer</button></div>{choosingCustomer&&<div><input aria-label="Search customer" placeholder="Search customer or pet" value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)}/>{customerResults.map(c=><button className="gp-customer-result" key={c.id} onClick={()=>chooseCustomer(c)}>{c.firstName} {c.lastName}</button>)}{pendingOwner&&<div><p>Move this ticket and its service lines to {pendingOwner.firstName} {pendingOwner.lastName}, for:</p><select aria-label="New owner dog" value={replacementPet} onChange={e=>setReplacementPet(e.target.value)}>{pendingOwner.pets.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={!replacementPet||busy} onClick={changeCustomer}>Apply customer</button></div>}</div>}<small className="gp-pos-id">Customer ID: {ticket.customer.id||'Choose customer'}</small><div className="gp-pos-pets">{(ticketId?ticket.pets.map((p:any)=>p.pet):customerPets).map((p:any)=><span key={p.id}>{!ticketId&&<input type="checkbox" aria-label={`Include ${p.name}`} checked={ticket.pets.some((v:any)=>v.pet.id===p.id)} onChange={e=>setTicket({...ticket,pets:e.target.checked?[...ticket.pets,{pet:p}]:ticket.pets.filter((v:any)=>v.pet.id!==p.id)})}/>}<button className="gp-btn" onClick={()=>setOwnerView({id:ticket.customer.id,petId:p.id})}>{p.name}</button><small>{p.breed||'Breed not set'}</small></span>)}</div><div className="gp-pos-inline"><strong>Owes {money(account.balanceCents)}</strong><strong>Credit {money(account.creditCents)}</strong></div><small>Daycare: {ticket.daycareStatus==='STAYING'?'Staying':'Not added'} · Rewards: {account.loyaltyPoints} pts · {cardOnFile?'Card on file':'No card on file'}</small></section>
 </header>
 <nav className="gp-pos-tabs" aria-label="Ticket sections">{["Items","VIP Memberships","Rebook","Account & Rewards","History","Notes"].map(name=><button className="gp-btn" aria-pressed={panel===name} key={name} onClick={()=>setPanel(name)}>{name}</button>)}</nav>
 <main className="gp-pos-body">
 {panel==="Items"&&<PosItems lines={ticket.lines} pets={ticket.pets.map((p:any)=>p.pet)} employees={employees} catalog={catalog} disabled={busy||terminal} onAdd={item=>void itemAction('add',item)} onEdit={(i,patch)=>void itemAction('edit',patch,i)} onRemove={i=>void itemAction('remove',null,i)} onPet={petId=>setOwnerView({id:ticket.customer.id,petId})}/>}
 {panel==="VIP Memberships"&&(ticket.customer.id?<MembershipEnrollment key={ticket.customer.id} plans={catalog.plans.filter((p:any)=>p.active)} initialCustomerId={ticket.customer.id}/>:<p>Choose a customer to enroll a dog.</p>)}
 {panel==="Rebook"&&!ticketId&&<p>Save this ticket to rebook it.</p>}{panel==="Rebook"&&!!ticketId&&<div className="gp-pos-panel">{ticket.status!=="CANCELLED"&&ticket.status!=="NO_SHOW"&&<div className="gp-field" style={{marginTop:18,paddingTop:16,borderTop:"1px solid #ddd"}}><span className="gp-label">Rebook This Appointment</span><div style={{display:"flex",gap:6,flexWrap:"wrap",margin:"8px 0"}}>{Array.from({length:12},(_,i)=>i+1).map(w=><button key={w} type="button" className="gp-btn" onClick={()=>chooseWeeks(w)}>{w} {w===1?"week":"weeks"}</button>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr auto",gap:8,alignItems:"end"}}><div><span className="gp-label">New Date / Time</span><input className="gp-search-input" type="datetime-local" value={rebookStart} onChange={e=>setRebookStart(e.target.value)}/></div><div><span className="gp-label">Preferred Groomer</span><select className="gp-search-input" value={groomerId} onChange={e=>setGroomerId(e.target.value)}><option value="">Choose later</option>{groomers.map(e=><option key={e.id} value={e.id}>{e.firstName} {e.lastName}</option>)}</select></div><button className="gp-btn primary" disabled={rebooking||!rebookStart} onClick={rebook}>{rebooking?"Rebooking…":"REBOOK"}</button></div>{confirmWarning&&<label style={{display:"block",marginTop:10,fontWeight:700}}><input type="checkbox" checked={confirmWarning} onChange={e=>setConfirmWarning(e.target.checked)}/> Confirm the nearby appointment warning and rebook anyway.</label>}</div>}</div>}
 {panel==="Account & Rewards"&&<div className="gp-pos-panel">
 <div className="gp-field" style={{marginTop:18,paddingTop:16,borderTop:"1px solid #ddd"}}><span className="gp-label">Manager Account Adjustment</span><div style={{display:"grid",gridTemplateColumns:"140px 140px 1fr auto",gap:8,alignItems:"end"}}><select className="gp-search-input" value={accountType} onChange={e=>setAccountType(e.target.value)}><option value="CREDIT">Customer Credit</option><option value="OWED">Amount Owed</option></select><input className="gp-search-input" placeholder="Amount cents" value={accountAmount} onChange={e=>setAccountAmount(e.target.value)}/><input className="gp-search-input" placeholder="Reason" value={accountReason} onChange={e=>setAccountReason(e.target.value)}/><button className="gp-btn" disabled={adjusting} onClick={adjustAccount}>{adjusting?"Saving…":"ADJUST"}</button></div></div>
 {rewards.length>0&&<div className="gp-field" style={{marginTop:18,paddingTop:16,borderTop:"1px solid #ddd"}}><span className="gp-label">Secret Rewards — Sales Team</span><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}>{rewards.map(r=><button key={r.id} className="gp-btn" disabled={account.loyaltyPoints<r.pointsCost||!!redeeming} onClick={()=>redeemReward(r)}>{redeeming===r.id?"Redeeming…":`${r.name} — ${r.pointsCost} pts`}</button>)}</div></div>}</div>}
 {panel==="History"&&<div className="gp-pos-panel"><h3>Ticket History</h3><div className="gp-list">{ticket.scheduleHistory.map((h:any,i:number)=><div className="gp-list-row" key={`${h.changedAt}-${i}`}><div><strong>{h.changeType}</strong><span>{h.actor?`${h.actor.firstName} ${h.actor.lastName}`:"GroomPro System"}</span></div><div><span>{h.previousStart?`${new Date(h.previousStart).toLocaleString()} → `:""}{new Date(h.newStart).toLocaleString()}</span></div></div>)}</div></div>}
 {panel==="Notes"&&<div className="gp-pos-panel"><h3>Ticket notes</h3>{ticketId?<p>{ticket.notes||"No notes on this ticket."}</p>:<textarea aria-label="Ticket notes" value={ticket.notes||""} onChange={e=>setTicket({...ticket,notes:e.target.value})}/>}</div>}
 </main><footer className="gp-pos-footer"><section className="gp-pos-footer-general"><h2>General</h2>{!ticketId&&<button className="gp-btn primary" disabled={busy} onClick={()=>saveTicket()}>{busy?"Saving…":"Save / Schedule"}</button>}{bookingWarning&&<p role="alert">{error} <button className="gp-btn" disabled={busy} onClick={()=>saveTicket(true)}>Schedule despite conflict</button></p>}<button className="gp-btn" onClick={async()=>{if(ticketId||await saveTicket())onClose()}}>Schedule / Leave Open</button>{!!ticketId&&ticket.status!=="CLOSED"&&ticket.status!=="CANCELLED"&&ticket.status!=="NO_SHOW"&&<div style={{marginBottom:16}}><button className="gp-btn" style={{fontWeight:900}} disabled={noShowing} onClick={processNoShow}>{noShowing?"Processing…":"MARK NO-SHOW — PROCESS FEE"}</button><small style={{display:"block",marginTop:5}}>{cardOnFile?"Card on file will be charged when Clover is connected.":"Without a card on file, the No-Show Fee becomes customer account balance owed."}</small></div>}</section><section className="gp-pos-totals"><h2>Totals</h2>{!ticketId&&<strong>{money(ticket.lines.reduce((sum:number,l:any)=>sum+(l.totalCents||0),0))}</strong>}{checkout&&<><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,margin:"8px 0"}}><div>Subtotal<br/><strong>{money(checkout.subtotalCents)}</strong></div><div>Sales Tax (cents)<br/><input className="gp-search-input" value={tax} onChange={e=>setTax(e.target.value)}/></div><div>Tip (cents)<br/><input className="gp-search-input" value={tip} onChange={e=>setTip(e.target.value)}/></div></div><div style={{display:"flex",justifyContent:"space-between",fontSize:18,fontWeight:800,margin:"8px 0"}}><span>Total {money(checkout.totalCents)}</span><span>Paid {money(checkout.paidCents)}</span><span>Due {money(checkout.dueCents)}</span></div></>}</section><section className="gp-pos-checkout"><h2>Payment</h2>{!ticketId&&<p>Save this ticket to collect payment here.</p>}{checkout&&ticket.status!=="CANCELLED"&&ticket.status!=="NO_SHOW"&&<>{checkout.dueCents>0&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr auto",gap:8,alignItems:"end"}}><div><span className="gp-label">Payment Type</span><select className="gp-search-input" value={paymentType} onChange={e=>setPaymentType(e.target.value)}><option>CASH</option><option>VISA</option><option>MASTERCARD</option><option>AMEX</option><option>DISCOVER</option><option>DEBIT</option><option>GIFT_CARD</option><option>OTHER</option></select></div><div><span className="gp-label">Amount (cents)</span><input className="gp-search-input" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/></div><button className="gp-btn primary" disabled={paying} onClick={recordPayment}>{paying?"Processing…":"RECORD PAYMENT"}</button></div>}<button className="gp-btn primary" style={{marginTop:10}} disabled={closing||checkout.dueCents!==0||ticket.status==="CLOSED"} onClick={closeTicket}>{closing?"Closing…":"CHECK OUT / CLOSE"}</button></>}</section></footer>
 </>}
 </PosWindowFrame>{ownerView&&<CustomerProfile customerId={ownerView.id} initialPetId={ownerView.petId} onClose={()=>void closeOwner()}/>}</>}

