"use client";
import {createContext,useContext,useEffect,useState} from 'react';
import {employeeFetch} from '../lib/employee-fetch';
import {dateKey,dateRange,shiftDate,parseDate,effectiveShift,scheduleDays,DateOverride} from '../lib/schedule-dates';
export const ScheduleRangeContext=createContext<{start:string;end:string;setStart:(v:string)=>void;setEnd:(v:string)=>void}|null>(null);
export type ScheduleResource={id:string;name:string;detail:string;active:boolean;slots:{id:string;dayOfWeek:number;startTime:string;endTime:string;active?:boolean|number}[]};
function clock(t:string){const[h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'am':'pm'}`}
export function ScheduleBoard({kind,resources,onEdit,onReload}:{kind:'employee'|'asset';resources:ScheduleResource[];onEdit:(id:string)=>void;onReload:()=>Promise<void>}){
 const[localStart,setLocalStart]=useState(()=>{const d=new Date();d.setDate(d.getDate()-d.getDay());return dateKey(d)}),[localEnd,setLocalEnd]=useState(()=>{const d=new Date();d.setDate(d.getDate()-d.getDay()+6);return dateKey(d)}),[overrides,setOverrides]=useState<DateOverride[]>([]),[selected,setSelected]=useState<{resource:ScheduleResource;date:string;scope:string;slotId?:string;off:boolean;start:string;end:string}|null>(null),[query,setQuery]=useState(''),[inactive,setInactive]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const sharedRange=useContext(ScheduleRangeContext);const start=sharedRange?.start??localStart,end=sharedRange?.end??localEnd,setStart=sharedRange?.setStart??setLocalStart,setEnd=sharedRange?.setEnd??setLocalEnd;
 let dates:string[]=[],rangeError='';try{dates=dateRange(start,end)}catch(e){rangeError=(e as Error).message}
 async function loadOverrides(){const r=await employeeFetch(`/api/schedule-overrides?start=${start}&end=${end}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not load schedules.');setOverrides(d.overrides||[])}
 useEffect(()=>{let live=true;setSelected(null);if(rangeError){setLoading(false);return}setLoading(true);setError('');employeeFetch(`/api/schedule-overrides?start=${start}&end=${end}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(live)setOverrides(d.overrides||[])}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[start,end,rangeError]);
 function move(n:number){try{setStart(shiftDate(start,n));setEnd(shiftDate(end,n))}catch{setError('Choose valid dates first.')}}
 async function save(startTime:string,endTime:string,reset=false){if(!selected)return;setBusy(true);setError('');setNotice('');try{let url='/api/schedule-overrides',method=reset?'DELETE':'PUT',body:object={resourceKind:kind,resourceId:selected.resource.id,date:selected.date,dayOff:selected.off,startTime,endTime};if(!reset&&selected.scope==='weekly'){url=kind==='employee'?'/api/employee-schedules':'/api/booking-assets/schedules';const dayOfWeek=parseDate(selected.date).getDay(),slot=selected.resource.slots.find(s=>selected.slotId?s.id===selected.slotId:Number(s.dayOfWeek)===dayOfWeek);if(selected.off){if(slot){method='DELETE';body={...(kind==='employee'?{userId:selected.resource.id}:{assetId:selected.resource.id}),dayOfWeek}}else{setSelected(null);setNotice('This weekday already has no recurring hours.');return}}else body={id:slot?.id,...(kind==='employee'?{userId:selected.resource.id}:{assetId:selected.resource.id}),dayOfWeek,startTime,endTime}}const r=await employeeFetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'Save failed.');await onReload();await loadOverrides();setSelected(null);setNotice(reset?'Date now follows the recurring schedule.':'Schedule saved.')}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
 return <section><p>Click a time spot to edit that date or make it recurring. Click {kind==='employee'?"an employee’s name to edit that employee":"a booking asset’s name to edit that asset"}.</p><div className="gp-staff-week-toolbar"><button type="button" className="gp-btn" disabled={busy} onClick={()=>move(-7)}>Previous week</button><button type="button" className="gp-btn" disabled={busy} onClick={()=>{const d=new Date();d.setDate(d.getDate()-d.getDay());const a=dateKey(d);setStart(a);setEnd(shiftDate(a,6))}}>This week</button><button type="button" className="gp-btn" disabled={busy} onClick={()=>move(7)}>Next week</button><label>From <input type="date" aria-label="Schedule start date" value={start} onChange={e=>setStart(e.target.value)} onBlur={e=>setStart(e.currentTarget.value)}/></label><label>Through <input type="date" aria-label="Schedule end date" value={end} onChange={e=>setEnd(e.target.value)} onBlur={e=>setEnd(e.currentTarget.value)}/></label></div><div className="gp-staff-week-toolbar"><input aria-label={`Find ${kind}`} placeholder={`Find ${kind==='employee'?'employee':'booking asset'}`} value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={inactive} onChange={e=>setInactive(e.target.checked)}/> Include inactive</label><span className="gp-shift working">Working</span><span className="gp-shift off">Off / no hours</span><small>Up to 31 days · Date-specific changes override weekly hours.</small></div>{(error||rangeError)&&<p role="alert">{rangeError||error}</p>}{notice&&<p role="status">{notice}</p>}
 {selected&&<form className="gp-settings-card" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void save(String(data.get('start')||''),String(data.get('end')||''))}}><h3>{selected.resource.name} · {selected.date}</h3><fieldset disabled={busy} className="gp-staff-week-editor"><label>Apply change to<select value={selected.scope} onChange={e=>setSelected({...selected,scope:e.target.value})}><option value="date">This date only</option><option value="weekly">Repeat every {scheduleDays[parseDate(selected.date).getDay()]}</option></select></label>{selected.scope==='weekly'&&selected.resource.slots.filter(s=>Number(s.dayOfWeek)===parseDate(selected.date).getDay()).length>1&&<label>Recurring shift<select value={selected.slotId} onChange={e=>{const slot=selected.resource.slots.find(s=>s.id===e.target.value)!;setSelected({...selected,slotId:slot.id,start:slot.startTime,end:slot.endTime})}}>{selected.resource.slots.filter(s=>Number(s.dayOfWeek)===parseDate(selected.date).getDay()).map(s=><option key={s.id} value={s.id}>{clock(s.startTime)} - {clock(s.endTime)}</option>)}</select></label>}<label><input type="checkbox" checked={selected.off} onChange={e=>setSelected({...selected,off:e.target.checked})}/> Day off / unavailable</label>{!selected.off&&<><label>Start<input key={`start-${selected.date}-${selected.slotId}`} name="start" type="time" required defaultValue={selected.start}/></label><label>End<input key={`end-${selected.date}-${selected.slotId}`} name="end" type="time" required defaultValue={selected.end}/></label></>}<button className="gp-btn primary">Save schedule</button>{overrides.some(o=>o.resourceId===selected.resource.id&&o.resourceKind===kind&&o.date===selected.date)&&<button type="button" className="gp-btn" onClick={()=>void save('','',true)}>Use recurring hours for this date</button>}<button type="button" className="gp-btn" onClick={()=>setSelected(null)}>Cancel</button></fieldset>{selected.scope==='weekly'&&<p>Changes this weekday’s recurring hours. Day off clears all shifts on that weekday. Existing date-specific exceptions remain in place.</p>}</form>}
 {!rangeError&&!error&&(loading?<p>Loading date-specific schedules…</p>:<div className="gp-staff-week-scroll"><table className="gp-staff-week-grid" style={{minWidth:Math.max(820,175+dates.length*115)}}><thead><tr><th>{kind==='employee'?'Employee':'Booking asset'}</th>{dates.map(date=><th key={date}>{scheduleDays[parseDate(date).getDay()]}<small style={{display:'block'}}>{date}</small></th>)}</tr></thead><tbody>{resources.filter(r=>(inactive||r.active)&&`${r.name} ${r.detail}`.toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id}><th><button disabled={busy} className="gp-staff-week-name" onClick={()=>{setSelected(null);onEdit(r.id)}}>{r.name}<small>{r.detail}{!r.active?' · Inactive':''}</small></button></th>{dates.map(date=>{const shift=effectiveShift(r.slots,overrides,kind,r.id,date),exception=overrides.some(o=>o.resourceKind===kind&&o.resourceId===r.id&&o.date===date);return <td key={date}><button type="button" disabled={busy} className={`gp-shift ${shift?'working':'off'}`} aria-label={`${r.name}, ${date}: ${shift?`${clock(shift.startTime)} to ${clock(shift.endTime)}`:'Off'}`} onClick={()=>setSelected({resource:r,date,scope:'date',slotId:r.slots.find(s=>Number(s.dayOfWeek)===parseDate(date).getDay())?.id,off:!shift,start:shift?.startTime||'08:30',end:shift?.endTime||'17:00'})}>{shift?<>{clock(shift.startTime)}<br/>{clock(shift.endTime)}</>:'Off'}{exception&&<small>This date only</small>}{!exception&&r.slots.filter(s=>s.active!==false&&s.active!==0&&Number(s.dayOfWeek)===parseDate(date).getDay()).slice(1).map(s=><small key={s.id}>{clock(s.startTime)} - {clock(s.endTime)}</small>)}</button></td>})}</tr>)}</tbody></table></div>)}
 </section>
}
