"use client";
import {useEffect,useMemo,useState} from "react";
import {EmployeeWeek} from "./employee-week";
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
type Asset={id:string;name:string;category:string;active:boolean;onlineBookingRecipient:boolean;schedules:{id:string;dayOfWeek:number;startTime:string;endTime:string}[]};
export function StaffAvailabilitySettings(){
 const[assets,setAssets]=useState<Asset[]>([]),[locations,setLocations]=useState<{id:string;name:string}[]>([]),[tab,setTab]=useState<"employees"|"assets">("employees"),[message,setMessage]=useState("");
 async function load(){try{const[a,l]=await Promise.all([fetch("/api/booking-assets",{cache:"no-store"}),fetch("/api/locations",{cache:"no-store"})]);if(a.ok)setAssets((await a.json()).assets||[]);if(l.ok)setLocations((await l.json()).locations||[])}catch{setMessage("Could not load booking availability.")}}
 useEffect(()=>{void load()},[]);
 async function setAssetDay(assetId:string,day:number,start:string,end:string){const r=await fetch("/api/booking-assets/schedules",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId,dayOfWeek:day,startTime:start,endTime:end})});if(!r.ok)setMessage((await r.json()).error||"Could not save asset schedule.");else{setMessage("Booking availability saved.");await load()}}
 async function addAsset(){const name=window.prompt("Asset name");if(!name)return;const category=window.prompt("Online booking category",name.toUpperCase().replace(/[^A-Z0-9]+/g,"_"));if(!category)return;const locationId=locations[0]?.id;if(!locationId){setMessage("A location is required.");return}const r=await fetch("/api/booking-assets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locationId,name,category})});setMessage(r.ok?"Asset added.":(await r.json()).error||"Could not add asset.");await load()}
 return <div className="gp-settings-card gp-settings-wide"><div className="gp-settings-card-head"><div><h2>Staff & Online Booking Availability</h2><p>Manage employees, PINs, recurring work schedules, booking assets, and asset availability.</p></div><div className="gp-bulk-controls"><button className={`gp-btn ${tab==="employees"?"primary":""}`} onClick={()=>setTab("employees")}>Employees</button><button className={`gp-btn ${tab==="assets"?"primary":""}`} onClick={()=>setTab("assets")}>Booking Assets</button></div></div>{message&&<div role="status">{message}</div>}{tab==="employees"?<EmployeeWeek/>:<><button className="gp-btn primary" onClick={addAsset}>+ Add Booking Asset</button><div style={{overflowX:"auto",marginTop:16}}>{assets.map(a=><AssetRow key={a.id} a={a} setDay={setAssetDay}/>)}</div></>}</div>
}
function AssetRow({a,setDay}:{a:Asset;setDay:(id:string,d:number,s:string,en:string)=>void}){const byDay=useMemo(()=>Object.fromEntries(a.schedules.map(s=>[s.dayOfWeek,s])),[a.schedules]);return <div className="gp-settings-card" style={{marginTop:10}}><strong>{a.name}</strong><span style={{marginLeft:12,opacity:.7}}>{a.category}</span><div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(130px,1fr))",gap:8,marginTop:10}}>{days.map((d,i)=>{const s=byDay[i+1];return <label key={d}><small>{d}</small><input type="time" value={s?.startTime||"08:30"} onChange={e=>setDay(a.id,i+1,e.target.value,s?.endTime||"17:00")}/><input type="time" value={s?.endTime||"17:00"} onChange={e=>setDay(a.id,i+1,s?.startTime||"08:30",e.target.value)}/></label>})}</div></div>}
