"use client";
import { useEffect,useMemo,useState } from "react";
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const roles=["ADMIN","MANAGER","FLOOR_MANAGER","FRONT","BACK","MASTER_GROOMER","GROOMER","SALES"];
const dayNum=(i:number)=>i+1;
type Employee={id:string;firstName:string;lastName:string;role:string;active:boolean;locationId:string|null};
type Asset={id:string;name:string;category:string;active:boolean;onlineBookingRecipient:boolean;schedules:{id:string;dayOfWeek:number;startTime:string;endTime:string}[]};
export function StaffAvailabilitySettings(){const[employees,setEmployees]=useState<Employee[]>([]);const[assets,setAssets]=useState<Asset[]>([]);const[locations,setLocations]=useState<{id:string;name:string}[]>([]);const[tab,setTab]=useState<"employees"|"assets">("employees");const[message,setMessage]=useState("");const[form,setForm]=useState({firstName:"",lastName:"",role:"FRONT",pin:"",locationId:""});
 async function load(){const[e,a,l]=await Promise.all([fetch("/api/employees",{cache:"no-store"}),fetch("/api/booking-assets",{cache:"no-store"}),fetch("/api/locations",{cache:"no-store"})]);if(e.ok)setEmployees((await e.json()).employees||[]);if(a.ok)setAssets((await a.json()).assets||[]);if(l.ok)setLocations((await l.json()).locations||[])}useEffect(()=>{load()},[]);
 async function addEmployee(){const r=await fetch("/api/employees",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setMessage(r.ok?"Employee added.":d.error||"Could not add employee.");if(r.ok){setForm({firstName:"",lastName:"",role:"FRONT",pin:"",locationId:""});await load()}}
 async function toggleEmployee(e:Employee){const r=await fetch("/api/employees",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:e.id,active:!e.active})});setMessage(r.ok?"Employee updated.":"Could not update employee.");await load()}
 async function setEmployeeDay(userId:string,day:number,start:string,end:string){const r=await fetch("/api/employee-schedules",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,dayOfWeek:day,startTime:start,endTime:end})});if(!r.ok){setMessage((await r.json()).error||"Could not save schedule.");return false}setMessage("Schedule saved.");return true}
 async function setAssetDay(assetId:string,day:number,start:string,end:string){const r=await fetch("/api/booking-assets/schedules",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId,dayOfWeek:day,startTime:start,endTime:end})});if(!r.ok)setMessage((await r.json()).error||"Could not save asset schedule.");else{setMessage("Booking availability saved.");await load()}}
 async function addAsset(){const name=window.prompt("Asset name");if(!name)return;const category=window.prompt("Online booking category",name.toUpperCase().replace(/[^A-Z0-9]+/g,"_"));if(!category)return;const locationId=locations[0]?.id;if(!locationId){setMessage("A location is required.");return}const r=await fetch("/api/booking-assets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locationId,name,category})});setMessage(r.ok?"Asset added.":(await r.json()).error||"Could not add asset.");await load()}
 return <div className="gp-settings-card gp-settings-wide"><div className="gp-settings-card-head"><div><h2>Staff & Online Booking Availability</h2><p>Manage employees, PINs, recurring work schedules, booking assets, and asset availability.</p></div><div className="gp-bulk-controls"><button className={`gp-btn ${tab==="employees"?"primary":""}`} onClick={()=>setTab("employees")}>Employees</button><button className={`gp-btn ${tab==="assets"?"primary":""}`} onClick={()=>setTab("assets")}>Booking Assets</button></div></div>{message&&<div className="gp-form-success">{message}</div>}{tab==="employees"?<><div className="gp-pricing-row" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 120px 150px auto",gap:8,alignItems:"end"}}><label>First name<input value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label>Last name<input value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>PIN<input inputMode="numeric" maxLength={10} value={form.pin} onChange={e=>setForm({...form,pin:e.target.value.replace(/\D/g,"")})}/></label><label>Location<select value={form.locationId} onChange={e=>setForm({...form,locationId:e.target.value})}><option value="">None</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><button className="gp-btn primary" onClick={addEmployee}>Add Employee</button></div><div style={{overflowX:"auto",marginTop:16}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Employee</th><th>Role</th>{days.map(d=><th key={d}>{d.slice(0,3)}</th>)}<th>Status</th></tr></thead><tbody>{employees.map(e=><EmployeeRow key={e.id} e={e} onToggle={toggleEmployee} setDay={setEmployeeDay}/>)}</tbody></table></div></>:<><button className="gp-btn primary" onClick={addAsset}>+ Add Booking Asset</button><div style={{overflowX:"auto",marginTop:16}}>{assets.map(a=><AssetRow key={a.id} a={a} setDay={setAssetDay}/>)}</div></>}</div>}
function EmployeeRow({e,onToggle,setDay}:{e:Employee;onToggle:(e:Employee)=>void;setDay:(id:string,d:number,s:string,en:string)=>Promise<boolean>}){const[schedules,setSchedules]=useState<Record<number,{start:string;end:string;id?:string}>>({});async function loadSchedules(){const r=await fetch("/api/employee-schedules",{cache:"no-store"});if(!r.ok)return;const d=await r.json();const x:Record<number,{start:string;end:string;id?:string}>={};(d.schedules||[]).filter((s:any)=>s.userId===e.id).forEach((s:any)=>x[Number(s.dayOfWeek)]={start:String(s.startTime),end:String(s.endTime),id:String(s.id)});setSchedules(x)}useEffect(()=>{loadSchedules().catch(()=>{})},[e.id]);async function enableDay(day:number){if(await setDay(e.id,day,"08:30","17:00"))await loadSchedules()}async function disableDay(s:{id?:string}){if(!s.id)return;const r=await fetch("/api/employee-schedules",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:s.id})});if(r.ok)await loadSchedules()}async function saveDay(day:number,s:{start:string;end:string}){if(await setDay(e.id,day,s.start,s.end))await loadSchedules()}return <tr><td>{e.firstName} {e.lastName}</td><td>{e.role}</td>{days.map((_,i)=>{const d=dayNum(i),s=schedules[d];return <td key={d}><input type="checkbox" checked={!!s} onChange={ev=>ev.target.checked?enableDay(d):s&&disableDay(s)}/>{s&&<><input type="time" value={s.start} onChange={ev=>setSchedules({...schedules,[d]:{...s,start:ev.target.value}})} onBlur={()=>saveDay(d,schedules[d])}/><input type="time" value={s.end} onChange={ev=>setSchedules({...schedules,[d]:{...s,end:ev.target.value}})} onBlur={()=>saveDay(d,schedules[d])}/></>}</td>})}<td><button className="gp-btn" onClick={()=>onToggle(e)}>{e.active?"Active":"Inactive"}</button></td></tr>}
function AssetRow({a,setDay}:{a:Asset;setDay:(id:string,d:number,s:string,en:string)=>void}){const byDay=useMemo(()=>Object.fromEntries(a.schedules.map(s=>[s.dayOfWeek,s])),[a.schedules]);return <div className="gp-settings-card" style={{marginTop:10}}><strong>{a.name}</strong><span style={{marginLeft:12,opacity:.7}}>{a.category}</span><div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(130px,1fr))",gap:8,marginTop:10}}>{days.map((d,i)=>{const s=byDay[i+1];return <label key={d}><small>{d}</small><input type="time" value={s?.startTime||"08:30"} onChange={e=>setDay(a.id,i+1,e.target.value,s?.endTime||"17:00")}/><input type="time" value={s?.endTime||"17:00"} onChange={e=>setDay(a.id,i+1,s?.startTime||"08:30",e.target.value)}/></label>})}</div></div>}
