"use client";
import { useEffect, useMemo, useState } from "react";

type Ticket={id:string;orderNumber:number;scheduledStart:string|null;status?:string;customer:{firstName:string;lastName:string};pets:{pet:{name:string}}[];lines:{description:string}[]};
export function TicketsWorkspace({date,onOpenTicket,onNewTicket}:{date:Date;onOpenTicket:(id:string)=>void;onNewTicket:()=>void}){
 const[tickets,setTickets]=useState<Ticket[]>([]);const[query,setQuery]=useState("");const[status,setStatus]=useState("ALL");const[loading,setLoading]=useState(true);
 useEffect(()=>{const start=new Date(date);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);setLoading(true);fetch(`/api/calendar?start=${encodeURIComponent(start.toISOString())}&end=${encodeURIComponent(end.toISOString())}`).then(r=>r.ok?r.json():{tickets:[]}).then(d=>setTickets(d.tickets||[])).catch(()=>setTickets([])).finally(()=>setLoading(false))},[date]);
 const filtered=useMemo(()=>tickets.filter(t=>{const text=`${t.orderNumber} ${t.customer.firstName} ${t.customer.lastName} ${t.pets.map(p=>p.pet.name).join(" ")} ${t.lines.map(l=>l.description).join(" ")}`.toLowerCase();return(!query.trim()||text.includes(query.trim().toLowerCase()))&&(status==="ALL"||t.status===status)}),[tickets,query,status]);
 return <section className="gp-calendar"><div className="gp-calendar-head" style={{padding:24}}><div><h1 className="gp-title">Tickets</h1><p className="gp-subtitle">Appointments, services, customers and ticket status for {date.toLocaleDateString()}.</p></div><div className="gp-actions"><button className="gp-btn primary" onClick={onNewTicket}>+ New Ticket</button></div></div><div style={{padding:"0 24px 24px"}}><div className="gp-form-grid"><input className="gp-search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, customer, pet, or service"/><select className="gp-search-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{["OPEN","CONFIRMED","CHECKED_IN","IN_PROGRESS","READY","CLOSED","CANCELLED"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div>{loading?<div className="gp-search-empty">Loading tickets…</div>:filtered.length?<div className="gp-search-results">{filtered.map(t=><button key={t.id} className="gp-customer-result" onClick={()=>onOpenTicket(t.id)}><div><strong>#{t.orderNumber} · {t.customer.firstName} {t.customer.lastName}</strong><span>{t.pets.map(p=>p.pet.name).join(", ")||"No pet listed"} · {t.lines[0]?.description||"No service listed"}</span></div><div><span>{t.scheduledStart?new Date(t.scheduledStart).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}):"Unscheduled"}</span><b>{t.status||"OPEN"}</b></div></button>)}</div>:<div className="gp-search-empty">No tickets match the current filters.</div>}</div></section>;
}
