"use client";
import {employeeFetch} from "../lib/employee-fetch";
import { useEffect, useMemo, useState } from "react";

type Ticket={id:string;orderNumber:number;scheduledStart:string|null;status?:string;customer:{firstName:string;lastName:string};pets:{pet:{name:string}}[];lines:{description:string}[]};
export function TicketsWorkspace({date,onOpenTicket,onNewTicket}:{date:Date;onOpenTicket:(id:string)=>void;onNewTicket:()=>void}){
 const[tickets,setTickets]=useState<Ticket[]>([]);const[query,setQuery]=useState("");const[status,setStatus]=useState("ALL");const[loading,setLoading]=useState(true);
 const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const[from,setFrom]=useState(()=>localDate(date)),[through,setThrough]=useState(()=>localDate(date)),[error,setError]=useState('');
 function preset(name:string){const start=new Date(),end=new Date();if(name==='Tomorrow'){start.setDate(start.getDate()+1);end.setDate(end.getDate()+1)}else if(name.includes('Week')){const offset=name==='Last Week'?-7:name==='Next Week'?7:0;start.setDate(start.getDate()-((start.getDay()+6)%7)+offset);end.setTime(+start);end.setDate(end.getDate()+6)}setFrom(localDate(start));setThrough(localDate(end))}
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');employeeFetch(`/api/tickets/list?from=${from}&through=${through}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d}).then(d=>setTickets(d.tickets||[])).catch(e=>{if(!c.signal.aborted)setError(String(e))}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[from,through]);
 const filtered=useMemo(()=>tickets.filter(t=>{const text=`${t.orderNumber} ${t.customer.firstName} ${t.customer.lastName} ${t.pets.map(p=>p.pet.name).join(" ")} ${t.lines.map(l=>l.description).join(" ")}`.toLowerCase();return(!query.trim()||text.includes(query.trim().toLowerCase()))&&(status==="ALL"||t.status===status)}),[tickets,query,status]);
 return <section className="gp-calendar"><div className="gp-calendar-head" style={{padding:24}}><div><h1 className="gp-title">Tickets</h1><p className="gp-subtitle">Appointments, services, customers and ticket status from {from} through {through}.</p></div><div className="gp-actions"><button className="gp-btn primary" onClick={onNewTicket}>+ New Ticket</button></div></div><div style={{padding:"0 24px 24px"}}><div className="gp-staff-week-toolbar">{["Today","Tomorrow","Last Week","This Week","Next Week"].map(name=><button className="gp-btn" key={name} onClick={()=>preset(name)}>{name}</button>)}<label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" value={through} onChange={e=>setThrough(e.target.value)}/></label></div>{error&&<p role="alert">{error}</p>}<div className="gp-form-grid"><input className="gp-search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, customer, pet, or service"/><select className="gp-search-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All Tickets</option>{["OPEN","CONFIRMED","CHECKED_IN","IN_PROGRESS","READY","CLOSED","CANCELLED","VOIDED","NO_SHOW"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div>{loading?<div className="gp-search-empty">Loading tickets…</div>:filtered.length?<div className="gp-search-results">{filtered.map(t=><button key={t.id} className="gp-customer-result" onClick={()=>onOpenTicket(t.id)}><div><strong>#{t.orderNumber} · {t.customer.firstName} {t.customer.lastName}</strong><span>{t.pets.map(p=>p.pet.name).join(", ")||"No pet listed"} · {t.lines[0]?.description||"No service listed"}</span></div><div><span>{t.scheduledStart?new Date(t.scheduledStart).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}):"Unscheduled"}</span><b>{t.status||"OPEN"}</b></div></button>)}</div>:<div className="gp-search-empty">No tickets match the current filters.</div>}</div></section>;
}
