"use client";
import { useEffect, useMemo, useState } from "react";
type Customer={id:string;firstName:string;lastName:string;pets:{id:string;name:string;breed:string|null}[]};
type Service={id:string;name:string;category:string|null;priceCents:number;durationMin:number};
type Product={id:string;name:string;sku:string|null;priceCents:number;quantity:number};
type Employee={id:string;firstName:string;lastName:string;role:string};
type Line={type:"SERVICE"|"PRODUCT";id:string;petId?:string;quantity:number};
export function TicketWindow({date,onClose,onSaved,initialCustomerId}:{date:Date;onClose:()=>void;onSaved:()=>void;initialCustomerId?:string|null}){
 const[query,setQuery]=useState("");const[customers,setCustomers]=useState<Customer[]>([]);const[customer,setCustomer]=useState<Customer|null>(null);const[petIds,setPetIds]=useState<string[]>([]);const[services,setServices]=useState<Service[]>([]);const[products,setProducts]=useState<Product[]>([]);const[employees,setEmployees]=useState<Employee[]>([]);const[lines,setLines]=useState<Line[]>([]);const[time,setTime]=useState("09:00");const[groomerId,setGroomerId]=useState("");const[notes,setNotes]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/services"),fetch("/api/products"),fetch("/api/employees")]).then(async([a,b,c])=>{const[sa,pb,ec]=await Promise.all([a.json(),b.json(),c.json()]);setServices(sa.services||[]);setProducts(pb.products||[]);setEmployees((ec.employees||[]).filter((e:Employee)=>["GROOMER","MASTER_GROOMER"].includes(e.role)))})},[]);
 useEffect(()=>{if(!initialCustomerId)return;fetch(`/api/customers/${initialCustomerId}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{const c=d.customer as Customer;setCustomer(c);setQuery(`${c.firstName} ${c.lastName}`);setPetIds(c.pets[0]?[c.pets[0].id]:[]) }).catch(()=>undefined)},[initialCustomerId]);
 useEffect(()=>{const q=query.trim();if(q.length<2||customer){setCustomers([]);return}const controller=new AbortController();const timer=window.setTimeout(()=>fetch(`/api/customers/search?q=${encodeURIComponent(q)}`,{signal:controller.signal}).then(r=>r.ok?r.json():{customers:[]}).then(d=>setCustomers(d.customers||[])).catch(()=>undefined),250);return()=>{clearTimeout(timer);controller.abort()}},[query,customer]);
 const total=useMemo(()=>lines.reduce((sum,l)=>{const item=l.type==="SERVICE"?services.find(s=>s.id===l.id):products.find(p=>p.id===l.id);return sum+(item?.priceCents||0)*l.quantity},0),[lines,services,products]);
 const duration=useMemo(()=>Math.max(15,lines.filter(l=>l.type==="SERVICE").reduce((sum,l)=>sum+(services.find(s=>s.id===l.id)?.durationMin||0),0)||30),[lines,services]);
 function choose(c:Customer){setCustomer(c);setQuery(`${c.firstName} ${c.lastName}`);setCustomers([]);setPetIds(c.pets[0]?[c.pets[0].id]:[])}
 function addLine(type:"SERVICE"|"PRODUCT",id:string){setLines(x=>[...x,{type,id,quantity:1,petId:type==="SERVICE"?petIds[0]:undefined}])}
 function removeLine(i:number){setLines(x=>x.filter((_,n)=>n!==i))}
 async function save(){if(!customer||!petIds.length||!lines.length){setError("Customer, at least one pet, and one service or product are required.");return}setSaving(true);setError("");const start=new Date(date);const[h,m]=time.split(":").map(Number);start.setHours(h,m,0,0);try{const r=await fetch("/api/tickets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId:customer.id,petIds,lines,scheduledStart:start.toISOString(),durationMin:duration,groomerId:groomerId||undefined,notes})});const d=await r.json();if(!r.ok){setError(d.error||"Ticket could not be created.");return}onSaved()}catch{setError("Ticket could not be created.")}finally{setSaving(false)}}
 return <div className="gp-floating-window gp-ticket-window" role="dialog" aria-modal="true"><div className="gp-floating-head"><div><div className="gp-floating-title">Ticket / Appointment</div><div className="gp-floating-subtitle">One transaction for appointment, services and merchandise</div></div><button className="gp-btn" onClick={onClose}>Close</button></div><div className="gp-profile-body">
 <label className="gp-field"><span className="gp-label">Customer</span><input autoFocus className="gp-search-input" value={query} onChange={e=>{setQuery(e.target.value);setCustomer(null);setPetIds([])}} placeholder="Search existing customer"/>{customers.length>0&&<div className="gp-search-results">{customers.map(c=><button className="gp-customer-result" key={c.id} onClick={()=>choose(c)}><strong>{c.firstName} {c.lastName}</strong><span>{c.pets.map(p=>p.name).join(", ")||"No pets"}</span></button>)}</div>}</label>
 {customer&&<label className="gp-field"><span className="gp-label">Pets</span><select multiple className="gp-search-input" value={petIds} onChange={e=>setPetIds(Array.from(e.target.selectedOptions).map(o=>o.value))}>{customer.pets.map(p=><option key={p.id} value={p.id}>{p.name}{p.breed?` · ${p.breed}`:""}</option>)}</select><small>Select one or more pets.</small></label>}
 <div className="gp-form-grid"><label className="gp-field"><span className="gp-label">Add Service</span><select className="gp-search-input" value="" onChange={e=>{if(e.target.value)addLine("SERVICE",e.target.value)}}><option value="">Select service…</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · ${(s.priceCents/100).toFixed(2)} · {s.durationMin} min</option>)}</select></label><label className="gp-field"><span className="gp-label">Appointment Time</span><input className="gp-search-input" type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div>
 <label className="gp-field"><span className="gp-label">Add Merchandise</span><select className="gp-search-input" value="" onChange={e=>{if(e.target.value)addLine("PRODUCT",e.target.value)}}><option value="">Select product…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · ${(p.priceCents/100).toFixed(2)} · {p.quantity} in stock</option>)}</select></label>
 <div className="gp-list">{lines.map((l,i)=>{const item=l.type==="SERVICE"?services.find(s=>s.id===l.id):products.find(p=>p.id===l.id);return <div className="gp-list-row" key={`${l.type}-${l.id}-${i}`}><div><strong>{item?.name||"Item"}</strong><span>{l.type}{l.type==="SERVICE"&&l.petId?` · ${customer?.pets.find(p=>p.id===l.petId)?.name||"Pet"}`:""}</span></div><div><input aria-label="Quantity" type="number" min={1} value={l.quantity} onChange={e=>setLines(x=>x.map((v,n)=>n===i?{...v,quantity:Math.max(1,Number(e.target.value)||1)}:v))} style={{width:60}}/><button className="gp-btn" onClick={()=>removeLine(i)}>Remove</button></div></div>})}</div>
 <div className="gp-form-grid"><label className="gp-field"><span className="gp-label">Groomer</span><select className="gp-search-input" value={groomerId} onChange={e=>setGroomerId(e.target.value)}><option value="">Assign later</option>{employees.map(e=><option key={e.id} value={e.id}>{e.firstName} {e.lastName}</option>)}</select></label><div className="gp-ticket-total"><span>Total</span><strong>${(total/100).toFixed(2)}</strong><small>{duration} min</small></div></div>
 <label className="gp-field"><span className="gp-label">Notes</span><textarea className="gp-search-input" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Ticket / grooming notes"/></label>{error&&<div className="gp-form-error">{error}</div>}</div><div className="gp-profile-footer"><button className="gp-btn" onClick={onClose}>Cancel</button><button className="gp-btn primary" disabled={saving} onClick={save}>{saving?"Saving…":"Create Ticket"}</button></div></div>}
