"use client";
import { useEffect, useMemo, useState } from "react";

type Employee = { id:string; firstName:string; lastName:string; role:string; active?:boolean };
type PetRow = { petId:string; pet:{ id:string; name:string; breed:string|null }; vipAvailability:"AVAILABLE"|"NOT_AVAILABLE"|"NEEDS_MORE_SESSIONS"|null; analSituation:"DONE_REQUESTED"|"DONE_NOT_REQUESTED"|"NOT_NEEDED"|null };
type Line = { id:string; role:string; assignedUserId?:string|null; assignedAt?:string|null; assignedUser:{id:string;firstName:string;lastName:string}|null; pet:{id:string;name:string}|null; description:string };
type Ticket = { id:string; orderNumber:number; scheduledStart:string|null; status:string; checkedInAt:string|null; arrivalPriority:number|null; daycareStatus:"NONE"|"STAYING"; pets:PetRow[]; lines:Line[] };
function vipIcon(status:PetRow["vipAvailability"]){if(status==="AVAILABLE")return "💙";if(status==="NOT_AVAILABLE")return "❌";return ""}
function analIcon(status:PetRow["analSituation"]){if(status==="DONE_REQUESTED")return "✅";if(status==="DONE_NOT_REQUESTED")return "⚠️";if(status==="NOT_NEEDED")return "🚫";return ""}
function timeLabel(value:string|null){return value?new Date(value).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}):""}
function keyFor(d:Date){const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,"0");const day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function defaultPushDate(base:Date){const d=new Date(base);d.setHours(12,0,0,0);d.setDate(d.getDate()+1);if(new Date(base).getDay()===6)d.setDate(d.getDate()+1);return d}

export function Whiteboard({date=new Date()}:{date?:Date}){
  const [tickets,setTickets]=useState<Ticket[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [snapshot,setSnapshot]=useState<{snapshotAt:string;itemCount:number}|null>(null);const [pushing,setPushing]=useState(false);const [pushDate,setPushDate]=useState(keyFor(defaultPushDate(new Date())));
  const dateKey=useMemo(()=>keyFor(new Date(date)),[date]);
  async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/whiteboard?date=${dateKey}`);if(!r.ok)throw new Error("Whiteboard data could not be loaded.");const d=await r.json();setTickets(d.tickets||[]);setSnapshot(d.snapshot||null);setEmployees(d.employees||[])}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  useEffect(()=>{load();const timer=window.setInterval(load,30000);return()=>window.clearInterval(timer)},[dateKey]);
  async function patch(payload:Record<string,unknown>){const r=await fetch("/api/whiteboard",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||"Whiteboard update failed.")}await load()}
  async function pushSelected(){setPushing(true);setError("");try{const r=await fetch("/api/whiteboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date:pushDate})});const body=await r.json();if(!r.ok)throw new Error(body.error||"Whiteboard could not be pushed.");await load()}catch(e){setError((e as Error).message)}finally{setPushing(false)}}
  const sorted=[...tickets].sort((a,b)=>a.orderNumber-b.orderNumber);
  const priorityOptions=Array.from({length:Math.max(12,sorted.length)},(_,i)=>i+1);const assignmentOptions=employees.filter(e=>["GROOMER","MASTER_GROOMER","FRONT","BACK","SALES","FLOOR_MANAGER","MANAGER","ADMIN"].includes(e.role));
  const columns=useMemo(()=>({left:sorted.filter(t=>{const h=t.scheduledStart?new Date(t.scheduledStart).getHours():0;return h<11}),right:sorted.filter(t=>{const h=t.scheduledStart?new Date(t.scheduledStart).getHours():0;return h>=11})}),[sorted]);
  const headers=["SCH TIME","ORDER #","NAME","BREED","FW / GR / VIP","PREPARED BY","WASHED BY","ANAL","GROOMED BY","DONE?","DAYCARE","PICKED UP?"];
  function TicketBlock({t}:{t:Ticket}){return <>{t.pets.map((pet,petIndex)=>{const prep=t.lines.find(l=>l.role==="PREP"&&l.pet?.id===pet.petId)?.assignedUser||null;const bath=t.lines.find(l=>l.role==="BATH"&&l.pet?.id===pet.petId)?.assignedUser||null;const groomLine=t.lines.find(l=>l.role==="GROOM"&&l.pet?.id===pet.petId);const groomEligible=Boolean(t.checkedInAt&&prep&&bath);const groom=groomEligible?(groomLine?.assignedUser||null):null;
      const assignment=(role:"PREP"|"BATH"|"GROOM",current:{id:string;firstName:string;lastName:string}|null)=><select aria-label={`${role} employee for ${pet.pet.name}`} disabled={role==="GROOM"&&!groomEligible} value={current?.id||""} onChange={e=>patch({ticketId:t.id,action:"ASSIGN",petId:pet.petId,lineRole:role,userId:e.target.value||null})} style={{fontSize:15,fontWeight:700,width:"100%",minHeight:38,textAlign:"center",background:"transparent",border:0}}><option value="">—</option>{assignmentOptions.map(e=><option key={e.id} value={e.id}>{e.firstName} {e.lastName.charAt(0)}.</option>)}</select>;
      return <div key={`${t.id}-${pet.petId}`} style={{display:"grid",gridTemplateColumns:"72px 68px minmax(110px,1.2fr) minmax(100px,1fr) 92px 118px 118px 72px 118px 70px 78px 82px",alignItems:"center",minHeight:52,padding:"1px 4px",gap:2,fontSize:18,borderBottom:petIndex===t.pets.length-1?"2px solid rgba(40,70,90,.55)":"0",background:t.status==="READY"?"#b9e8ef":(petIndex%2===0?"rgba(255,255,255,.24)":"rgba(255,255,255,.08)")}}><div style={{textAlign:"center",fontWeight:700}}>{timeLabel(t.scheduledStart)}</div><div style={{textAlign:"center"}}>{petIndex===0?<select value={t.arrivalPriority??""} onChange={e=>patch({ticketId:t.id,action:"PRIORITY",value:e.target.value?Number(e.target.value):null})} style={{fontSize:18,fontWeight:800,width:62,minHeight:38,textAlign:"center",background:"transparent",border:0}}><option value="">—</option>{priorityOptions.map(n=><option key={n} value={n}>{n}</option>)}</select>:""}</div><div style={{fontWeight:800,textAlign:"center"}}>{pet.pet.name}</div><div style={{textAlign:"center",fontSize:15}}>{pet.pet.breed||"—"}</div><div style={{textAlign:"center",fontWeight:800}}>{vipIcon(pet.vipAvailability)}</div><div style={{textAlign:"center"}}>{assignment("PREP",prep)}</div><div style={{textAlign:"center"}}>{assignment("BATH",bath)}</div><div style={{textAlign:"center",fontSize:22}}>{analIcon(pet.analSituation)}</div><div style={{textAlign:"center"}}>{assignment("GROOM",groom)}</div><div style={{textAlign:"center",fontSize:23}}>{t.status==="READY"?"💙":""}</div><div style={{textAlign:"center",fontSize:24}}>{t.daycareStatus==="STAYING"?"🐾":""}</div><div style={{textAlign:"center",fontSize:21}}>{t.status==="CLOSED"?"✓":""}</div></div>})}<div style={{height:30}} aria-label="Reserved same-day appointment space" /></>}
  function Half({items}:{items:Ticket[]}){return <div style={{minWidth:0}}>{items.map(t=><TicketBlock key={t.id} t={t}/>)}</div>}
  function Header(){return <div style={{display:"grid",gridTemplateColumns:"72px 68px minmax(110px,1.2fr) minmax(100px,1fr) 92px 118px 118px 72px 118px 70px 78px 82px",fontWeight:800,fontSize:12,textAlign:"center",padding:"6px 4px",background:"#4b55c7",color:"white",gap:2}}>{headers.map(h=><div key={h} style={{lineHeight:1.05}}>{h}</div>)}</div>}
  return <div style={{height:"100%",width:"100%",background:"#cfecef",fontFamily:"Arial,sans-serif",overflow:"auto",touchAction:"manipulation"}}>
    <div style={{position:"sticky",top:0,zIndex:6,background:"#4b55c7",color:"white",padding:"7px 10px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div style={{fontWeight:900,fontSize:20}}>WE WASH UNTIL THE WATER RUNS CLEAR</div><div style={{display:"flex",alignItems:"center",gap:7}}><label style={{fontWeight:800,fontSize:15}}>PUSH DATE</label><input type="date" value={pushDate} onChange={e=>setPushDate(e.target.value)} style={{minHeight:40,fontSize:16,fontWeight:700,padding:"0 7px",borderRadius:6,border:0}}/><button onClick={pushSelected} disabled={pushing||!pushDate} style={{minHeight:40,padding:"0 14px",fontSize:16,fontWeight:900,border:0,borderRadius:7,cursor:pushing?"wait":"pointer"}}>{pushing?"PUSHING…":"PUSH DATE TO WHITEBOARD"}</button></div></div>
    {snapshot&&<div style={{background:"white",padding:"4px 10px",fontSize:13,fontWeight:700}}>Prepared Whiteboard: {snapshot.itemCount} scheduled appointments · pushed {new Date(snapshot.snapshotAt).toLocaleString()}</div>}
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",background:"#4b55c7",color:"white",fontWeight:800,fontSize:15,padding:"7px 4px",gap:4}}><div style={{textAlign:"center"}}>8:30 AM – 10:30 AM</div><div style={{textAlign:"center"}}>11:00 AM – 4:30 PM</div></div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:4,padding:"0 4px"}}><Header/><Header/></div>
    {loading?<div style={{padding:40,textAlign:"center",fontSize:28}}>Loading Whiteboard…</div>:error?<div style={{padding:40,textAlign:"center",fontSize:24}}>{error}</div>:<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:4,padding:"0 4px"}}><Half items={columns.left}/><Half items={columns.right}/></div>}
    <div style={{position:"sticky",bottom:0,padding:"7px 12px",background:"#4b55c7",color:"white",fontWeight:700,fontSize:14,textAlign:"center"}}>Priority is touch-selected on the Whiteboard; Front Desk can also enter a priority number. Groomed By stays blank until the dog has arrived and both Prepared By and Washed By are assigned. Reserved spaces are intentionally left between appointment blocks for same-day additions.</div>
  </div>
}
