import {writeAudit} from '@/src/lib/audit';
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/src/lib/db";
import {getActiveEmployeeSession} from "@/src/lib/employee-session";
import { hashPin, hashPinPrefixes, pinAssignmentError } from "@/src/lib/pin";
const validRoles=["ADMIN","MANAGER","FLOOR_MANAGER","FRONT","BACK","MASTER_GROOMER","GROOMER","SALES"];
async function authorize(request:NextRequest,tenantId:string){
 const sid=request.cookies.get("groompro_session")?.value;const session=sid?await getActiveEmployeeSession(tenantId,sid):null;
 if(!session)return{denied:NextResponse.json({error:"Employee PIN is required."},{status:401})};
 if(!["ADMIN","MANAGER"].includes(session.user.role))return{denied:NextResponse.json({error:"An administrator or manager must sign in to edit employees."},{status:403})};
 return{session};
}
async function validateLocation(tenantId:string,id:unknown){return !id||!!await db.location.findFirst({where:{id:String(id),tenantId}});}
async function tenantIdFrom(request: NextRequest) { const explicit=request.headers.get("x-tenant-id") || request.cookies.get("groompro_tenant")?.value || process.env.GROOMPRO_DEV_TENANT_ID || null; return explicit; }
export async function GET(request: NextRequest) { const tenantId=await tenantIdFrom(request); if(!tenantId)return NextResponse.json({employees:[]}); const employees=await db.user.findMany({where:{tenantId},select:{id:true,firstName:true,lastName:true,role:true,jobTitle:true,active:true,locationId:true},orderBy:[{active:"desc"},{lastName:"asc"},{firstName:"asc"}]}); return NextResponse.json({employees}); }
export async function POST(request: NextRequest) { const tenantId=await tenantIdFrom(request); if(!tenantId)return NextResponse.json({error:"Tenant context is required."},{status:401}); const access=await authorize(request,tenantId);if(access.denied)return access.denied; const body=await request.json(); if(!await validateLocation(tenantId,body.locationId))return NextResponse.json({error:"Location not found."},{status:400}); if(body.role!==undefined&&!validRoles.includes(String(body.role)))return NextResponse.json({error:"Invalid role."},{status:400}); const firstName=String(body.firstName||"").trim(),lastName=String(body.lastName||"").trim(),role=String(body.role||"FRONT"),pin=String(body.pin||""); if(!firstName||!lastName)return NextResponse.json({error:"First and last name are required."},{status:400}); if(!/^\d{3,10}$/.test(pin))return NextResponse.json({error:"PIN must contain 4–10 digits."},{status:400}); const existing=await db.user.findFirst({where:{tenantId,firstName,lastName}}); if(existing)return NextResponse.json({error:"An employee with that name already exists."},{status:409}); let user;try{user=await saveWithPin(tenantId,pin,undefined,{tenantId,locationId:body.locationId?String(body.locationId):null,firstName,lastName,role:role as any,jobTitle:String(body.jobTitle||"").trim()||null,active:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"PIN assignment failed."},{status:409});} await writeAudit({tenantId,actorUserId:access.session!.user.id,entityType:"USER",entityId:user.id,action:request.method==="POST"?"CREATE":"EDIT",summary:"Updated employee profile.",details:{pinChanged:!!body.pin}});return NextResponse.json({employee:{id:user.id,firstName:user.firstName,lastName:user.lastName,role:user.role,active:user.active,locationId:user.locationId}},{status:201}); }
export async function PATCH(request: NextRequest) { const tenantId=await tenantIdFrom(request); if(!tenantId)return NextResponse.json({error:"Tenant context is required."},{status:401}); const access=await authorize(request,tenantId);if(access.denied)return access.denied; const body=await request.json(); if(!await validateLocation(tenantId,body.locationId))return NextResponse.json({error:"Location not found."},{status:400}); if(body.role!==undefined&&!validRoles.includes(String(body.role)))return NextResponse.json({error:"Invalid role."},{status:400}); const id=String(body.id||""); if(!id)return NextResponse.json({error:"Employee id is required."},{status:400}); const existing=await db.user.findFirst({where:{id,tenantId}}); if(!existing)return NextResponse.json({error:"Employee not found."},{status:404}); const data:any={}; if(body.jobTitle!==undefined)data.jobTitle=String(body.jobTitle).trim()||null; if((body.firstName!==undefined&&!String(body.firstName).trim())||(body.lastName!==undefined&&!String(body.lastName).trim()))return NextResponse.json({error:"First and last name are required."},{status:400}); if(body.firstName!==undefined)data.firstName=String(body.firstName).trim(); if(body.lastName!==undefined)data.lastName=String(body.lastName).trim(); if(body.role!==undefined)data.role=String(body.role) as any; if(body.locationId!==undefined)data.locationId=body.locationId?String(body.locationId):null; if(body.active!==undefined)data.active=Boolean(body.active); if(body.pin!==undefined&&String(body.pin)!==""){if(!/^\d{3,10}$/.test(String(body.pin)))return NextResponse.json({error:"PIN must contain 4–10 digits."},{status:400});} if(body.active===true&&!existing.active&&!String(body.pin||""))return NextResponse.json({error:"Enter a new PIN when reactivating an employee so its starting combination can be checked."},{status:400}); let user;try{user=String(body.pin||"")?await saveWithPin(tenantId,String(body.pin),id,data):await db.user.update({where:{id},data});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"PIN assignment failed."},{status:409});} await writeAudit({tenantId,actorUserId:access.session!.user.id,entityType:"USER",entityId:user.id,action:request.method==="POST"?"CREATE":"EDIT",summary:"Updated employee profile.",details:{pinChanged:!!body.pin}});return NextResponse.json({employee:{id:user.id,firstName:user.firstName,lastName:user.lastName,role:user.role,active:user.active,locationId:user.locationId}}); }

async function saveWithPin(tenantId:string,pin:string,id:string|undefined,data:any){
 const pinHash=await hashPin(pin),pinPrefixHashes=await hashPinPrefixes(pin);
 return db.$transaction(async tx=>{
  await tx.$queryRaw`SELECT id FROM Tenant WHERE id = ${tenantId} FOR UPDATE`;
  const others=await tx.user.findMany({where:{tenantId,active:true,...(id?{id:{not:id}}:{})},select:{pinHash:true,pinPrefixHashes:true}});
  const error=await pinAssignmentError(pin,others);if(error)throw new Error(error);
  return id?tx.user.update({where:{id},data:{...data,pinHash,pinPrefixHashes}}):tx.user.create({data:{...data,pinHash,pinPrefixHashes}});
 },{timeout:30000});
}
